// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * AppTheme selects the UI colour scheme.
 * </pre>
 *
 * Protobuf enum {@code bladewatch.v1.AppTheme}
 */
@com.google.protobuf.Generated
public enum AppTheme
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>APP_THEME_UNSPECIFIED = 0;</code>
   */
  APP_THEME_UNSPECIFIED(0),
  /**
   * <code>APP_THEME_DARK = 1;</code>
   */
  APP_THEME_DARK(1),
  /**
   * <code>APP_THEME_LIGHT = 2;</code>
   */
  APP_THEME_LIGHT(2),
  /**
   * <code>APP_THEME_AUTO = 3;</code>
   */
  APP_THEME_AUTO(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "AppTheme");
  }
  /**
   * <code>APP_THEME_UNSPECIFIED = 0;</code>
   */
  public static final int APP_THEME_UNSPECIFIED_VALUE = 0;
  /**
   * <code>APP_THEME_DARK = 1;</code>
   */
  public static final int APP_THEME_DARK_VALUE = 1;
  /**
   * <code>APP_THEME_LIGHT = 2;</code>
   */
  public static final int APP_THEME_LIGHT_VALUE = 2;
  /**
   * <code>APP_THEME_AUTO = 3;</code>
   */
  public static final int APP_THEME_AUTO_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AppTheme valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AppTheme forNumber(int value) {
    switch (value) {
      case 0: return APP_THEME_UNSPECIFIED;
      case 1: return APP_THEME_DARK;
      case 2: return APP_THEME_LIGHT;
      case 3: return APP_THEME_AUTO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AppTheme>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AppTheme> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AppTheme>() {
          public AppTheme findValueByNumber(int number) {
            return AppTheme.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Settings.getDescriptor().getEnumType(2);
  }

  private static final AppTheme[] VALUES = values();

  public static AppTheme valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AppTheme(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bladewatch.v1.AppTheme)
}

