// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * BatteryInfo carries the Android battery level and charge state.
 * </pre>
 *
 * Protobuf type {@code bladewatch.v1.BatteryInfo}
 */
@com.google.protobuf.Generated
public final class BatteryInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.BatteryInfo)
    BatteryInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "BatteryInfo");
  }
  // Use BatteryInfo.newBuilder() to construct.
  private BatteryInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatteryInfo() {
    level_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_BatteryInfo_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_BatteryInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_BatteryInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.BatteryInfo.class, net.bladewatch.app.grpc.v1.BatteryInfo.Builder.class);
  }

  public static final int LEVEL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object level_ = "";
  /**
   * <pre>
   * BatteryMonitor.getBatteryInfo() emits a STATUS STRING here (e.g. "NORMAL"),
   * not a numeric percentage (the percentage is carried by SocInfo.percent).
   * This was modeled as int32, which made strict JSON clients (connect-web)
   * reject the entire GetStatus response with a type error. No client reads
   * battery.level. The daemon also emits voltage/soc/lastUpdate alongside it,
   * which clients tolerate via jsonOptions.ignoreUnknownFields.
   * </pre>
   *
   * <code>string level = 1 [json_name = "level"];</code>
   * @return The level.
   */
  @java.lang.Override
  public java.lang.String getLevel() {
    java.lang.Object ref = level_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      level_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * BatteryMonitor.getBatteryInfo() emits a STATUS STRING here (e.g. "NORMAL"),
   * not a numeric percentage (the percentage is carried by SocInfo.percent).
   * This was modeled as int32, which made strict JSON clients (connect-web)
   * reject the entire GetStatus response with a type error. No client reads
   * battery.level. The daemon also emits voltage/soc/lastUpdate alongside it,
   * which clients tolerate via jsonOptions.ignoreUnknownFields.
   * </pre>
   *
   * <code>string level = 1 [json_name = "level"];</code>
   * @return The bytes for level.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLevelBytes() {
    java.lang.Object ref = level_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      level_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(level_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, level_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(level_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, level_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.BatteryInfo)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.BatteryInfo other = (net.bladewatch.app.grpc.v1.BatteryInfo) obj;

    if (!getLevel()
        .equals(other.getLevel())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.BatteryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.BatteryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.BatteryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.BatteryInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * BatteryInfo carries the Android battery level and charge state.
   * </pre>
   *
   * Protobuf type {@code bladewatch.v1.BatteryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.BatteryInfo)
      net.bladewatch.app.grpc.v1.BatteryInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_BatteryInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_BatteryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.BatteryInfo.class, net.bladewatch.app.grpc.v1.BatteryInfo.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.BatteryInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      level_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_BatteryInfo_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.BatteryInfo getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.BatteryInfo.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.BatteryInfo build() {
      net.bladewatch.app.grpc.v1.BatteryInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.BatteryInfo buildPartial() {
      net.bladewatch.app.grpc.v1.BatteryInfo result = new net.bladewatch.app.grpc.v1.BatteryInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.BatteryInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.level_ = level_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.BatteryInfo) {
        return mergeFrom((net.bladewatch.app.grpc.v1.BatteryInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.BatteryInfo other) {
      if (other == net.bladewatch.app.grpc.v1.BatteryInfo.getDefaultInstance()) return this;
      if (!other.getLevel().isEmpty()) {
        level_ = other.level_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              level_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object level_ = "";
    /**
     * <pre>
     * BatteryMonitor.getBatteryInfo() emits a STATUS STRING here (e.g. "NORMAL"),
     * not a numeric percentage (the percentage is carried by SocInfo.percent).
     * This was modeled as int32, which made strict JSON clients (connect-web)
     * reject the entire GetStatus response with a type error. No client reads
     * battery.level. The daemon also emits voltage/soc/lastUpdate alongside it,
     * which clients tolerate via jsonOptions.ignoreUnknownFields.
     * </pre>
     *
     * <code>string level = 1 [json_name = "level"];</code>
     * @return The level.
     */
    public java.lang.String getLevel() {
      java.lang.Object ref = level_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        level_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * BatteryMonitor.getBatteryInfo() emits a STATUS STRING here (e.g. "NORMAL"),
     * not a numeric percentage (the percentage is carried by SocInfo.percent).
     * This was modeled as int32, which made strict JSON clients (connect-web)
     * reject the entire GetStatus response with a type error. No client reads
     * battery.level. The daemon also emits voltage/soc/lastUpdate alongside it,
     * which clients tolerate via jsonOptions.ignoreUnknownFields.
     * </pre>
     *
     * <code>string level = 1 [json_name = "level"];</code>
     * @return The bytes for level.
     */
    public com.google.protobuf.ByteString
        getLevelBytes() {
      java.lang.Object ref = level_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        level_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * BatteryMonitor.getBatteryInfo() emits a STATUS STRING here (e.g. "NORMAL"),
     * not a numeric percentage (the percentage is carried by SocInfo.percent).
     * This was modeled as int32, which made strict JSON clients (connect-web)
     * reject the entire GetStatus response with a type error. No client reads
     * battery.level. The daemon also emits voltage/soc/lastUpdate alongside it,
     * which clients tolerate via jsonOptions.ignoreUnknownFields.
     * </pre>
     *
     * <code>string level = 1 [json_name = "level"];</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      level_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BatteryMonitor.getBatteryInfo() emits a STATUS STRING here (e.g. "NORMAL"),
     * not a numeric percentage (the percentage is carried by SocInfo.percent).
     * This was modeled as int32, which made strict JSON clients (connect-web)
     * reject the entire GetStatus response with a type error. No client reads
     * battery.level. The daemon also emits voltage/soc/lastUpdate alongside it,
     * which clients tolerate via jsonOptions.ignoreUnknownFields.
     * </pre>
     *
     * <code>string level = 1 [json_name = "level"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      level_ = getDefaultInstance().getLevel();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BatteryMonitor.getBatteryInfo() emits a STATUS STRING here (e.g. "NORMAL"),
     * not a numeric percentage (the percentage is carried by SocInfo.percent).
     * This was modeled as int32, which made strict JSON clients (connect-web)
     * reject the entire GetStatus response with a type error. No client reads
     * battery.level. The daemon also emits voltage/soc/lastUpdate alongside it,
     * which clients tolerate via jsonOptions.ignoreUnknownFields.
     * </pre>
     *
     * <code>string level = 1 [json_name = "level"];</code>
     * @param value The bytes for level to set.
     * @return This builder for chaining.
     */
    public Builder setLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      level_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.BatteryInfo)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.BatteryInfo)
  private static final net.bladewatch.app.grpc.v1.BatteryInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.BatteryInfo();
  }

  public static net.bladewatch.app.grpc.v1.BatteryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatteryInfo>
      PARSER = new com.google.protobuf.AbstractParser<BatteryInfo>() {
    @java.lang.Override
    public BatteryInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatteryInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatteryInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.BatteryInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

