// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/stream.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface EnableStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.EnableStreamRequest)
    com.google.protobuf.MessageOrBuilder {
}
