// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/recordings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface EventEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.EventEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 offset_ms = 1 [json_name = "offsetMs"];</code>
   * @return The offsetMs.
   */
  long getOffsetMs();

  /**
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string label = 3 [json_name = "label"];</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 3 [json_name = "label"];</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>double confidence = 4 [json_name = "confidence"];</code>
   * @return The confidence.
   */
  double getConfidence();
}
