// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetAppearanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetAppearanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string theme = 2 [json_name = "theme"];</code>
   * @return The theme.
   */
  java.lang.String getTheme();
  /**
   * <code>string theme = 2 [json_name = "theme"];</code>
   * @return The bytes for theme.
   */
  com.google.protobuf.ByteString
      getThemeBytes();

  /**
   * <pre>
   * BCP-47 locale tag or "auto".
   * </pre>
   *
   * <code>string locale = 3 [json_name = "locale"];</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <pre>
   * BCP-47 locale tag or "auto".
   * </pre>
   *
   * <code>string locale = 3 [json_name = "locale"];</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();
}
