// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/notifications.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.GetCategoriesResponse}
 */
@com.google.protobuf.Generated
public final class GetCategoriesResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.GetCategoriesResponse)
    GetCategoriesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "GetCategoriesResponse");
  }
  // Use GetCategoriesResponse.newBuilder() to construct.
  private GetCategoriesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetCategoriesResponse() {
    categoriesJson_ = "";
    vapidPublicKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_GetCategoriesResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_GetCategoriesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_GetCategoriesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.GetCategoriesResponse.class, net.bladewatch.app.grpc.v1.GetCategoriesResponse.Builder.class);
  }

  public static final int CATEGORIES_JSON_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object categoriesJson_ = "";
  /**
   * <pre>
   * Forwarded registry JSON blob from CategoryRegistry.rawJson().
   * </pre>
   *
   * <code>string categories_json = 1 [json_name = "categoriesJson"];</code>
   * @return The categoriesJson.
   */
  @java.lang.Override
  public java.lang.String getCategoriesJson() {
    java.lang.Object ref = categoriesJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      categoriesJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Forwarded registry JSON blob from CategoryRegistry.rawJson().
   * </pre>
   *
   * <code>string categories_json = 1 [json_name = "categoriesJson"];</code>
   * @return The bytes for categoriesJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoriesJsonBytes() {
    java.lang.Object ref = categoriesJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      categoriesJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VAPID_PUBLIC_KEY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vapidPublicKey_ = "";
  /**
   * <code>string vapid_public_key = 2 [json_name = "vapidPublicKey"];</code>
   * @return The vapidPublicKey.
   */
  @java.lang.Override
  public java.lang.String getVapidPublicKey() {
    java.lang.Object ref = vapidPublicKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vapidPublicKey_ = s;
      return s;
    }
  }
  /**
   * <code>string vapid_public_key = 2 [json_name = "vapidPublicKey"];</code>
   * @return The bytes for vapidPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVapidPublicKeyBytes() {
    java.lang.Object ref = vapidPublicKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vapidPublicKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(categoriesJson_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, categoriesJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(vapidPublicKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, vapidPublicKey_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(categoriesJson_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, categoriesJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(vapidPublicKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, vapidPublicKey_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.GetCategoriesResponse)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.GetCategoriesResponse other = (net.bladewatch.app.grpc.v1.GetCategoriesResponse) obj;

    if (!getCategoriesJson()
        .equals(other.getCategoriesJson())) return false;
    if (!getVapidPublicKey()
        .equals(other.getVapidPublicKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CATEGORIES_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getCategoriesJson().hashCode();
    hash = (37 * hash) + VAPID_PUBLIC_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getVapidPublicKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.GetCategoriesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.GetCategoriesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.GetCategoriesResponse)
      net.bladewatch.app.grpc.v1.GetCategoriesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_GetCategoriesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_GetCategoriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.GetCategoriesResponse.class, net.bladewatch.app.grpc.v1.GetCategoriesResponse.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.GetCategoriesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      categoriesJson_ = "";
      vapidPublicKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_GetCategoriesResponse_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.GetCategoriesResponse getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.GetCategoriesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.GetCategoriesResponse build() {
      net.bladewatch.app.grpc.v1.GetCategoriesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.GetCategoriesResponse buildPartial() {
      net.bladewatch.app.grpc.v1.GetCategoriesResponse result = new net.bladewatch.app.grpc.v1.GetCategoriesResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.GetCategoriesResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.categoriesJson_ = categoriesJson_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.vapidPublicKey_ = vapidPublicKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.GetCategoriesResponse) {
        return mergeFrom((net.bladewatch.app.grpc.v1.GetCategoriesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.GetCategoriesResponse other) {
      if (other == net.bladewatch.app.grpc.v1.GetCategoriesResponse.getDefaultInstance()) return this;
      if (!other.getCategoriesJson().isEmpty()) {
        categoriesJson_ = other.categoriesJson_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getVapidPublicKey().isEmpty()) {
        vapidPublicKey_ = other.vapidPublicKey_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              categoriesJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              vapidPublicKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object categoriesJson_ = "";
    /**
     * <pre>
     * Forwarded registry JSON blob from CategoryRegistry.rawJson().
     * </pre>
     *
     * <code>string categories_json = 1 [json_name = "categoriesJson"];</code>
     * @return The categoriesJson.
     */
    public java.lang.String getCategoriesJson() {
      java.lang.Object ref = categoriesJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoriesJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Forwarded registry JSON blob from CategoryRegistry.rawJson().
     * </pre>
     *
     * <code>string categories_json = 1 [json_name = "categoriesJson"];</code>
     * @return The bytes for categoriesJson.
     */
    public com.google.protobuf.ByteString
        getCategoriesJsonBytes() {
      java.lang.Object ref = categoriesJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoriesJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Forwarded registry JSON blob from CategoryRegistry.rawJson().
     * </pre>
     *
     * <code>string categories_json = 1 [json_name = "categoriesJson"];</code>
     * @param value The categoriesJson to set.
     * @return This builder for chaining.
     */
    public Builder setCategoriesJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      categoriesJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Forwarded registry JSON blob from CategoryRegistry.rawJson().
     * </pre>
     *
     * <code>string categories_json = 1 [json_name = "categoriesJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoriesJson() {
      categoriesJson_ = getDefaultInstance().getCategoriesJson();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Forwarded registry JSON blob from CategoryRegistry.rawJson().
     * </pre>
     *
     * <code>string categories_json = 1 [json_name = "categoriesJson"];</code>
     * @param value The bytes for categoriesJson to set.
     * @return This builder for chaining.
     */
    public Builder setCategoriesJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      categoriesJson_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object vapidPublicKey_ = "";
    /**
     * <code>string vapid_public_key = 2 [json_name = "vapidPublicKey"];</code>
     * @return The vapidPublicKey.
     */
    public java.lang.String getVapidPublicKey() {
      java.lang.Object ref = vapidPublicKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vapidPublicKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vapid_public_key = 2 [json_name = "vapidPublicKey"];</code>
     * @return The bytes for vapidPublicKey.
     */
    public com.google.protobuf.ByteString
        getVapidPublicKeyBytes() {
      java.lang.Object ref = vapidPublicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vapidPublicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vapid_public_key = 2 [json_name = "vapidPublicKey"];</code>
     * @param value The vapidPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setVapidPublicKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vapidPublicKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string vapid_public_key = 2 [json_name = "vapidPublicKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVapidPublicKey() {
      vapidPublicKey_ = getDefaultInstance().getVapidPublicKey();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string vapid_public_key = 2 [json_name = "vapidPublicKey"];</code>
     * @param value The bytes for vapidPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setVapidPublicKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vapidPublicKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.GetCategoriesResponse)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.GetCategoriesResponse)
  private static final net.bladewatch.app.grpc.v1.GetCategoriesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.GetCategoriesResponse();
  }

  public static net.bladewatch.app.grpc.v1.GetCategoriesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCategoriesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetCategoriesResponse>() {
    @java.lang.Override
    public GetCategoriesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCategoriesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCategoriesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.GetCategoriesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

