// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetChargeCapResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetChargeCapResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int32 percent = 2 [json_name = "percent"];</code>
   * @return The percent.
   */
  int getPercent();

  /**
   * <code>bool enabled = 3 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>bool supported = 4 [json_name = "supported"];</code>
   * @return The supported.
   */
  boolean getSupported();

  /**
   * <code>string error = 5 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 5 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
