// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetLocaleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetLocaleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Active BCP-47 locale tag.
   * </pre>
   *
   * <code>string lang = 1 [json_name = "lang"];</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <pre>
   * Active BCP-47 locale tag.
   * </pre>
   *
   * <code>string lang = 1 [json_name = "lang"];</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <pre>
   * All supported tags mapped to true.
   * </pre>
   *
   * <code>map&lt;string, bool&gt; supported = 2 [json_name = "supported"];</code>
   */
  int getSupportedCount();
  /**
   * <pre>
   * All supported tags mapped to true.
   * </pre>
   *
   * <code>map&lt;string, bool&gt; supported = 2 [json_name = "supported"];</code>
   */
  boolean containsSupported(
      java.lang.String key);
  /**
   * Use {@link #getSupportedMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Boolean>
  getSupported();
  /**
   * <pre>
   * All supported tags mapped to true.
   * </pre>
   *
   * <code>map&lt;string, bool&gt; supported = 2 [json_name = "supported"];</code>
   */
  java.util.Map<java.lang.String, java.lang.Boolean>
  getSupportedMap();
  /**
   * <pre>
   * All supported tags mapped to true.
   * </pre>
   *
   * <code>map&lt;string, bool&gt; supported = 2 [json_name = "supported"];</code>
   */
  boolean getSupportedOrDefault(
      java.lang.String key,
      boolean defaultValue);
  /**
   * <pre>
   * All supported tags mapped to true.
   * </pre>
   *
   * <code>map&lt;string, bool&gt; supported = 2 [json_name = "supported"];</code>
   */
  boolean getSupportedOrThrow(
      java.lang.String key);
}
