// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetModelsManifestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetModelsManifestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Full manifest JSON from /data/local/tmp/web/shared/models/manifest.json.
   * </pre>
   *
   * <code>string manifest_json = 1 [json_name = "manifestJson"];</code>
   * @return The manifestJson.
   */
  java.lang.String getManifestJson();
  /**
   * <pre>
   * Full manifest JSON from /data/local/tmp/web/shared/models/manifest.json.
   * </pre>
   *
   * <code>string manifest_json = 1 [json_name = "manifestJson"];</code>
   * @return The bytes for manifestJson.
   */
  com.google.protobuf.ByteString
      getManifestJsonBytes();
}
