// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetParkingDeltaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetParkingDeltaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Hours of history to consider (default 72).
   * </pre>
   *
   * <code>int32 max_age_hours = 1 [json_name = "maxAgeHours"];</code>
   * @return The maxAgeHours.
   */
  int getMaxAgeHours();
}
