// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/trips.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetSummaryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetSummaryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .bladewatch.v1.WeeklyRollupEntry summary = 2 [json_name = "summary"];</code>
   */
  java.util.List<net.bladewatch.app.grpc.v1.WeeklyRollupEntry> 
      getSummaryList();
  /**
   * <code>repeated .bladewatch.v1.WeeklyRollupEntry summary = 2 [json_name = "summary"];</code>
   */
  net.bladewatch.app.grpc.v1.WeeklyRollupEntry getSummary(int index);
  /**
   * <code>repeated .bladewatch.v1.WeeklyRollupEntry summary = 2 [json_name = "summary"];</code>
   */
  int getSummaryCount();
  /**
   * <code>repeated .bladewatch.v1.WeeklyRollupEntry summary = 2 [json_name = "summary"];</code>
   */
  java.util.List<? extends net.bladewatch.app.grpc.v1.WeeklyRollupEntryOrBuilder> 
      getSummaryOrBuilderList();
  /**
   * <code>repeated .bladewatch.v1.WeeklyRollupEntry summary = 2 [json_name = "summary"];</code>
   */
  net.bladewatch.app.grpc.v1.WeeklyRollupEntryOrBuilder getSummaryOrBuilder(
      int index);
}
