// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetSohNominalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetSohNominalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Present only when a nominal kWh has been set; absent means "unset".
   * </pre>
   *
   * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
   * @return Whether the nominalKwh field is set.
   */
  boolean hasNominalKwh();
  /**
   * <pre>
   * Present only when a nominal kWh has been set; absent means "unset".
   * </pre>
   *
   * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
   * @return The nominalKwh.
   */
  double getNominalKwh();

  /**
   * <pre>
   * "user", "auto", or "unset".
   * </pre>
   *
   * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
   * @return The nominalSource.
   */
  java.lang.String getNominalSource();
  /**
   * <pre>
   * "user", "auto", or "unset".
   * </pre>
   *
   * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
   * @return The bytes for nominalSource.
   */
  com.google.protobuf.ByteString
      getNominalSourceBytes();
}
