// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1 [json_name = "deviceId"];</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1 [json_name = "deviceId"];</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>bool vehicle_data_ready = 2 [json_name = "vehicleDataReady"];</code>
   * @return The vehicleDataReady.
   */
  boolean getVehicleDataReady();

  /**
   * <code>string app_version = 3 [json_name = "appVersion"];</code>
   * @return The appVersion.
   */
  java.lang.String getAppVersion();
  /**
   * <code>string app_version = 3 [json_name = "appVersion"];</code>
   * @return The bytes for appVersion.
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();

  /**
   * <pre>
   * Camera IDs currently recording.
   * </pre>
   *
   * <code>repeated int32 recording = 4 [json_name = "recording"];</code>
   * @return A list containing the recording.
   */
  java.util.List<java.lang.Integer> getRecordingList();
  /**
   * <pre>
   * Camera IDs currently recording.
   * </pre>
   *
   * <code>repeated int32 recording = 4 [json_name = "recording"];</code>
   * @return The count of recording.
   */
  int getRecordingCount();
  /**
   * <pre>
   * Camera IDs currently recording.
   * </pre>
   *
   * <code>repeated int32 recording = 4 [json_name = "recording"];</code>
   * @param index The index of the element to return.
   * @return The recording at the given index.
   */
  int getRecording(int index);

  /**
   * <pre>
   * Camera IDs in view-only mode.
   * </pre>
   *
   * <code>repeated int32 viewing = 5 [json_name = "viewing"];</code>
   * @return A list containing the viewing.
   */
  java.util.List<java.lang.Integer> getViewingList();
  /**
   * <pre>
   * Camera IDs in view-only mode.
   * </pre>
   *
   * <code>repeated int32 viewing = 5 [json_name = "viewing"];</code>
   * @return The count of viewing.
   */
  int getViewingCount();
  /**
   * <pre>
   * Camera IDs in view-only mode.
   * </pre>
   *
   * <code>repeated int32 viewing = 5 [json_name = "viewing"];</code>
   * @param index The index of the element to return.
   * @return The viewing at the given index.
   */
  int getViewing(int index);

  /**
   * <pre>
   * Camera IDs active (recording or view).
   * </pre>
   *
   * <code>repeated int32 active = 6 [json_name = "active"];</code>
   * @return A list containing the active.
   */
  java.util.List<java.lang.Integer> getActiveList();
  /**
   * <pre>
   * Camera IDs active (recording or view).
   * </pre>
   *
   * <code>repeated int32 active = 6 [json_name = "active"];</code>
   * @return The count of active.
   */
  int getActiveCount();
  /**
   * <pre>
   * Camera IDs active (recording or view).
   * </pre>
   *
   * <code>repeated int32 active = 6 [json_name = "active"];</code>
   * @param index The index of the element to return.
   * @return The active at the given index.
   */
  int getActive(int index);

  /**
   * <pre>
   * Camera IDs available on this device.
   * </pre>
   *
   * <code>repeated int32 available = 7 [json_name = "available"];</code>
   * @return A list containing the available.
   */
  java.util.List<java.lang.Integer> getAvailableList();
  /**
   * <pre>
   * Camera IDs available on this device.
   * </pre>
   *
   * <code>repeated int32 available = 7 [json_name = "available"];</code>
   * @return The count of available.
   */
  int getAvailableCount();
  /**
   * <pre>
   * Camera IDs available on this device.
   * </pre>
   *
   * <code>repeated int32 available = 7 [json_name = "available"];</code>
   * @param index The index of the element to return.
   * @return The available at the given index.
   */
  int getAvailable(int index);

  /**
   * <code>.bladewatch.v1.BatteryInfo battery = 8 [json_name = "battery"];</code>
   * @return Whether the battery field is set.
   */
  boolean hasBattery();
  /**
   * <code>.bladewatch.v1.BatteryInfo battery = 8 [json_name = "battery"];</code>
   * @return The battery.
   */
  net.bladewatch.app.grpc.v1.BatteryInfo getBattery();
  /**
   * <code>.bladewatch.v1.BatteryInfo battery = 8 [json_name = "battery"];</code>
   */
  net.bladewatch.app.grpc.v1.BatteryInfoOrBuilder getBatteryOrBuilder();

  /**
   * <code>bool acc = 9 [json_name = "acc"];</code>
   * @return The acc.
   */
  boolean getAcc();

  /**
   * <code>.bladewatch.v1.ChargingInfo charging = 10 [json_name = "charging"];</code>
   * @return Whether the charging field is set.
   */
  boolean hasCharging();
  /**
   * <code>.bladewatch.v1.ChargingInfo charging = 10 [json_name = "charging"];</code>
   * @return The charging.
   */
  net.bladewatch.app.grpc.v1.ChargingInfo getCharging();
  /**
   * <code>.bladewatch.v1.ChargingInfo charging = 10 [json_name = "charging"];</code>
   */
  net.bladewatch.app.grpc.v1.ChargingInfoOrBuilder getChargingOrBuilder();

  /**
   * <code>.bladewatch.v1.SocInfo soc = 11 [json_name = "soc"];</code>
   * @return Whether the soc field is set.
   */
  boolean hasSoc();
  /**
   * <code>.bladewatch.v1.SocInfo soc = 11 [json_name = "soc"];</code>
   * @return The soc.
   */
  net.bladewatch.app.grpc.v1.SocInfo getSoc();
  /**
   * <code>.bladewatch.v1.SocInfo soc = 11 [json_name = "soc"];</code>
   */
  net.bladewatch.app.grpc.v1.SocInfoOrBuilder getSocOrBuilder();

  /**
   * <code>.bladewatch.v1.RangeInfo range = 12 [json_name = "range"];</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <code>.bladewatch.v1.RangeInfo range = 12 [json_name = "range"];</code>
   * @return The range.
   */
  net.bladewatch.app.grpc.v1.RangeInfo getRange();
  /**
   * <code>.bladewatch.v1.RangeInfo range = 12 [json_name = "range"];</code>
   */
  net.bladewatch.app.grpc.v1.RangeInfoOrBuilder getRangeOrBuilder();

  /**
   * <code>.bladewatch.v1.SohInfo soh = 13 [json_name = "soh"];</code>
   * @return Whether the soh field is set.
   */
  boolean hasSoh();
  /**
   * <code>.bladewatch.v1.SohInfo soh = 13 [json_name = "soh"];</code>
   * @return The soh.
   */
  net.bladewatch.app.grpc.v1.SohInfo getSoh();
  /**
   * <code>.bladewatch.v1.SohInfo soh = 13 [json_name = "soh"];</code>
   */
  net.bladewatch.app.grpc.v1.SohInfoOrBuilder getSohOrBuilder();

  /**
   * <code>string distance_unit = 14 [json_name = "distanceUnit"];</code>
   * @return The distanceUnit.
   */
  java.lang.String getDistanceUnit();
  /**
   * <code>string distance_unit = 14 [json_name = "distanceUnit"];</code>
   * @return The bytes for distanceUnit.
   */
  com.google.protobuf.ByteString
      getDistanceUnitBytes();

  /**
   * <code>string locale = 15 [json_name = "locale"];</code>
   * @return The locale.
   */
  java.lang.String getLocale();
  /**
   * <code>string locale = 15 [json_name = "locale"];</code>
   * @return The bytes for locale.
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  /**
   * <code>bool safe_zone_suppressed = 16 [json_name = "safeZoneSuppressed"];</code>
   * @return The safeZoneSuppressed.
   */
  boolean getSafeZoneSuppressed();

  /**
   * <code>bool in_safe_zone = 17 [json_name = "inSafeZone"];</code>
   * @return The inSafeZone.
   */
  boolean getInSafeZone();

  /**
   * <code>string safe_zone_name = 18 [json_name = "safeZoneName"];</code>
   * @return The safeZoneName.
   */
  java.lang.String getSafeZoneName();
  /**
   * <code>string safe_zone_name = 18 [json_name = "safeZoneName"];</code>
   * @return The bytes for safeZoneName.
   */
  com.google.protobuf.ByteString
      getSafeZoneNameBytes();

  /**
   * <code>bool gpu_surveillance = 19 [json_name = "gpuSurveillance"];</code>
   * @return The gpuSurveillance.
   */
  boolean getGpuSurveillance();

  /**
   * <code>.bladewatch.v1.RecordingStatus recording_status = 20 [json_name = "recordingStatus"];</code>
   * @return Whether the recordingStatus field is set.
   */
  boolean hasRecordingStatus();
  /**
   * <code>.bladewatch.v1.RecordingStatus recording_status = 20 [json_name = "recordingStatus"];</code>
   * @return The recordingStatus.
   */
  net.bladewatch.app.grpc.v1.RecordingStatus getRecordingStatus();
  /**
   * <code>.bladewatch.v1.RecordingStatus recording_status = 20 [json_name = "recordingStatus"];</code>
   */
  net.bladewatch.app.grpc.v1.RecordingStatusOrBuilder getRecordingStatusOrBuilder();

  /**
   * <code>.bladewatch.v1.TripStatus trip_status = 21 [json_name = "tripStatus"];</code>
   * @return Whether the tripStatus field is set.
   */
  boolean hasTripStatus();
  /**
   * <code>.bladewatch.v1.TripStatus trip_status = 21 [json_name = "tripStatus"];</code>
   * @return The tripStatus.
   */
  net.bladewatch.app.grpc.v1.TripStatus getTripStatus();
  /**
   * <code>.bladewatch.v1.TripStatus trip_status = 21 [json_name = "tripStatus"];</code>
   */
  net.bladewatch.app.grpc.v1.TripStatusOrBuilder getTripStatusOrBuilder();

  /**
   * <pre>
   * Serialised JSON blob from GpsMonitor.getLocationJson().
   * </pre>
   *
   * <code>string gps_json = 22 [json_name = "gpsJson"];</code>
   * @return The gpsJson.
   */
  java.lang.String getGpsJson();
  /**
   * <pre>
   * Serialised JSON blob from GpsMonitor.getLocationJson().
   * </pre>
   *
   * <code>string gps_json = 22 [json_name = "gpsJson"];</code>
   * @return The bytes for gpsJson.
   */
  com.google.protobuf.ByteString
      getGpsJsonBytes();

  /**
   * <code>.bladewatch.v1.NetworkInfo network = 23 [json_name = "network"];</code>
   * @return Whether the network field is set.
   */
  boolean hasNetwork();
  /**
   * <code>.bladewatch.v1.NetworkInfo network = 23 [json_name = "network"];</code>
   * @return The network.
   */
  net.bladewatch.app.grpc.v1.NetworkInfo getNetwork();
  /**
   * <code>.bladewatch.v1.NetworkInfo network = 23 [json_name = "network"];</code>
   */
  net.bladewatch.app.grpc.v1.NetworkInfoOrBuilder getNetworkOrBuilder();

  /**
   * <pre>
   * Populated only when vehicle data block throws.
   * </pre>
   *
   * <code>string vehicle_data_error = 24 [json_name = "vehicleDataError"];</code>
   * @return The vehicleDataError.
   */
  java.lang.String getVehicleDataError();
  /**
   * <pre>
   * Populated only when vehicle data block throws.
   * </pre>
   *
   * <code>string vehicle_data_error = 24 [json_name = "vehicleDataError"];</code>
   * @return The bytes for vehicleDataError.
   */
  com.google.protobuf.ByteString
      getVehicleDataErrorBytes();
}
