// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/surveillance.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetSnapshotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetSnapshotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Quadrant index 0-3.
   * </pre>
   *
   * <code>int32 quadrant = 1 [json_name = "quadrant"];</code>
   * @return The quadrant.
   */
  int getQuadrant();
}
