// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.GetSohNominalResponse}
 */
@com.google.protobuf.Generated
public final class GetSohNominalResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.GetSohNominalResponse)
    GetSohNominalResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "GetSohNominalResponse");
  }
  // Use GetSohNominalResponse.newBuilder() to construct.
  private GetSohNominalResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetSohNominalResponse() {
    nominalSource_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_GetSohNominalResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_GetSohNominalResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_GetSohNominalResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.GetSohNominalResponse.class, net.bladewatch.app.grpc.v1.GetSohNominalResponse.Builder.class);
  }

  private int bitField0_;
  public static final int NOMINAL_KWH_FIELD_NUMBER = 1;
  private double nominalKwh_ = 0D;
  /**
   * <pre>
   * Present only when a nominal kWh has been set; absent means "unset".
   * </pre>
   *
   * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
   * @return Whether the nominalKwh field is set.
   */
  @java.lang.Override
  public boolean hasNominalKwh() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Present only when a nominal kWh has been set; absent means "unset".
   * </pre>
   *
   * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
   * @return The nominalKwh.
   */
  @java.lang.Override
  public double getNominalKwh() {
    return nominalKwh_;
  }

  public static final int NOMINAL_SOURCE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nominalSource_ = "";
  /**
   * <pre>
   * "user", "auto", or "unset".
   * </pre>
   *
   * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
   * @return The nominalSource.
   */
  @java.lang.Override
  public java.lang.String getNominalSource() {
    java.lang.Object ref = nominalSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nominalSource_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "user", "auto", or "unset".
   * </pre>
   *
   * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
   * @return The bytes for nominalSource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNominalSourceBytes() {
    java.lang.Object ref = nominalSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nominalSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeDouble(1, nominalKwh_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nominalSource_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nominalSource_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, nominalKwh_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nominalSource_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nominalSource_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.GetSohNominalResponse)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.GetSohNominalResponse other = (net.bladewatch.app.grpc.v1.GetSohNominalResponse) obj;

    if (hasNominalKwh() != other.hasNominalKwh()) return false;
    if (hasNominalKwh()) {
      if (java.lang.Double.doubleToLongBits(getNominalKwh())
          != java.lang.Double.doubleToLongBits(
              other.getNominalKwh())) return false;
    }
    if (!getNominalSource()
        .equals(other.getNominalSource())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNominalKwh()) {
      hash = (37 * hash) + NOMINAL_KWH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNominalKwh()));
    }
    hash = (37 * hash) + NOMINAL_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getNominalSource().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.GetSohNominalResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.GetSohNominalResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.GetSohNominalResponse)
      net.bladewatch.app.grpc.v1.GetSohNominalResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_GetSohNominalResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_GetSohNominalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.GetSohNominalResponse.class, net.bladewatch.app.grpc.v1.GetSohNominalResponse.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.GetSohNominalResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      nominalKwh_ = 0D;
      nominalSource_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_GetSohNominalResponse_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.GetSohNominalResponse getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.GetSohNominalResponse.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.GetSohNominalResponse build() {
      net.bladewatch.app.grpc.v1.GetSohNominalResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.GetSohNominalResponse buildPartial() {
      net.bladewatch.app.grpc.v1.GetSohNominalResponse result = new net.bladewatch.app.grpc.v1.GetSohNominalResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.GetSohNominalResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.nominalKwh_ = nominalKwh_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nominalSource_ = nominalSource_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.GetSohNominalResponse) {
        return mergeFrom((net.bladewatch.app.grpc.v1.GetSohNominalResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.GetSohNominalResponse other) {
      if (other == net.bladewatch.app.grpc.v1.GetSohNominalResponse.getDefaultInstance()) return this;
      if (other.hasNominalKwh()) {
        setNominalKwh(other.getNominalKwh());
      }
      if (!other.getNominalSource().isEmpty()) {
        nominalSource_ = other.nominalSource_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              nominalKwh_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 18: {
              nominalSource_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double nominalKwh_ ;
    /**
     * <pre>
     * Present only when a nominal kWh has been set; absent means "unset".
     * </pre>
     *
     * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
     * @return Whether the nominalKwh field is set.
     */
    @java.lang.Override
    public boolean hasNominalKwh() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Present only when a nominal kWh has been set; absent means "unset".
     * </pre>
     *
     * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
     * @return The nominalKwh.
     */
    @java.lang.Override
    public double getNominalKwh() {
      return nominalKwh_;
    }
    /**
     * <pre>
     * Present only when a nominal kWh has been set; absent means "unset".
     * </pre>
     *
     * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
     * @param value The nominalKwh to set.
     * @return This builder for chaining.
     */
    public Builder setNominalKwh(double value) {

      nominalKwh_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Present only when a nominal kWh has been set; absent means "unset".
     * </pre>
     *
     * <code>optional double nominal_kwh = 1 [json_name = "nominalKwh"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNominalKwh() {
      bitField0_ = (bitField0_ & ~0x00000001);
      nominalKwh_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object nominalSource_ = "";
    /**
     * <pre>
     * "user", "auto", or "unset".
     * </pre>
     *
     * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
     * @return The nominalSource.
     */
    public java.lang.String getNominalSource() {
      java.lang.Object ref = nominalSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nominalSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "user", "auto", or "unset".
     * </pre>
     *
     * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
     * @return The bytes for nominalSource.
     */
    public com.google.protobuf.ByteString
        getNominalSourceBytes() {
      java.lang.Object ref = nominalSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nominalSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "user", "auto", or "unset".
     * </pre>
     *
     * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
     * @param value The nominalSource to set.
     * @return This builder for chaining.
     */
    public Builder setNominalSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nominalSource_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "user", "auto", or "unset".
     * </pre>
     *
     * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNominalSource() {
      nominalSource_ = getDefaultInstance().getNominalSource();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "user", "auto", or "unset".
     * </pre>
     *
     * <code>string nominal_source = 2 [json_name = "nominalSource"];</code>
     * @param value The bytes for nominalSource to set.
     * @return This builder for chaining.
     */
    public Builder setNominalSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nominalSource_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.GetSohNominalResponse)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.GetSohNominalResponse)
  private static final net.bladewatch.app.grpc.v1.GetSohNominalResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.GetSohNominalResponse();
  }

  public static net.bladewatch.app.grpc.v1.GetSohNominalResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSohNominalResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSohNominalResponse>() {
    @java.lang.Override
    public GetSohNominalResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSohNominalResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSohNominalResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.GetSohNominalResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

