// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/trips.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetTelemetryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetTelemetryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .bladewatch.v1.TelemetrySample telemetry = 2 [json_name = "telemetry"];</code>
   */
  java.util.List<net.bladewatch.app.grpc.v1.TelemetrySample> 
      getTelemetryList();
  /**
   * <code>repeated .bladewatch.v1.TelemetrySample telemetry = 2 [json_name = "telemetry"];</code>
   */
  net.bladewatch.app.grpc.v1.TelemetrySample getTelemetry(int index);
  /**
   * <code>repeated .bladewatch.v1.TelemetrySample telemetry = 2 [json_name = "telemetry"];</code>
   */
  int getTelemetryCount();
  /**
   * <code>repeated .bladewatch.v1.TelemetrySample telemetry = 2 [json_name = "telemetry"];</code>
   */
  java.util.List<? extends net.bladewatch.app.grpc.v1.TelemetrySampleOrBuilder> 
      getTelemetryOrBuilderList();
  /**
   * <code>repeated .bladewatch.v1.TelemetrySample telemetry = 2 [json_name = "telemetry"];</code>
   */
  net.bladewatch.app.grpc.v1.TelemetrySampleOrBuilder getTelemetryOrBuilder(
      int index);

  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
