// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GetVehicleStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GetVehicleStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>.bladewatch.v1.DoorStatus doors = 2 [json_name = "doors"];</code>
   * @return Whether the doors field is set.
   */
  boolean hasDoors();
  /**
   * <code>.bladewatch.v1.DoorStatus doors = 2 [json_name = "doors"];</code>
   * @return The doors.
   */
  net.bladewatch.app.grpc.v1.DoorStatus getDoors();
  /**
   * <code>.bladewatch.v1.DoorStatus doors = 2 [json_name = "doors"];</code>
   */
  net.bladewatch.app.grpc.v1.DoorStatusOrBuilder getDoorsOrBuilder();

  /**
   * <code>.bladewatch.v1.WindowStatus windows = 3 [json_name = "windows"];</code>
   * @return Whether the windows field is set.
   */
  boolean hasWindows();
  /**
   * <code>.bladewatch.v1.WindowStatus windows = 3 [json_name = "windows"];</code>
   * @return The windows.
   */
  net.bladewatch.app.grpc.v1.WindowStatus getWindows();
  /**
   * <code>.bladewatch.v1.WindowStatus windows = 3 [json_name = "windows"];</code>
   */
  net.bladewatch.app.grpc.v1.WindowStatusOrBuilder getWindowsOrBuilder();

  /**
   * <code>.bladewatch.v1.VehicleCapabilities capabilities = 4 [json_name = "capabilities"];</code>
   * @return Whether the capabilities field is set.
   */
  boolean hasCapabilities();
  /**
   * <code>.bladewatch.v1.VehicleCapabilities capabilities = 4 [json_name = "capabilities"];</code>
   * @return The capabilities.
   */
  net.bladewatch.app.grpc.v1.VehicleCapabilities getCapabilities();
  /**
   * <code>.bladewatch.v1.VehicleCapabilities capabilities = 4 [json_name = "capabilities"];</code>
   */
  net.bladewatch.app.grpc.v1.VehicleCapabilitiesOrBuilder getCapabilitiesOrBuilder();

  /**
   * <code>.bladewatch.v1.TrunkStatus trunk = 5 [json_name = "trunk"];</code>
   * @return Whether the trunk field is set.
   */
  boolean hasTrunk();
  /**
   * <code>.bladewatch.v1.TrunkStatus trunk = 5 [json_name = "trunk"];</code>
   * @return The trunk.
   */
  net.bladewatch.app.grpc.v1.TrunkStatus getTrunk();
  /**
   * <code>.bladewatch.v1.TrunkStatus trunk = 5 [json_name = "trunk"];</code>
   */
  net.bladewatch.app.grpc.v1.TrunkStatusOrBuilder getTrunkOrBuilder();

  /**
   * <code>.bladewatch.v1.SunroofStatus sunroof = 6 [json_name = "sunroof"];</code>
   * @return Whether the sunroof field is set.
   */
  boolean hasSunroof();
  /**
   * <code>.bladewatch.v1.SunroofStatus sunroof = 6 [json_name = "sunroof"];</code>
   * @return The sunroof.
   */
  net.bladewatch.app.grpc.v1.SunroofStatus getSunroof();
  /**
   * <code>.bladewatch.v1.SunroofStatus sunroof = 6 [json_name = "sunroof"];</code>
   */
  net.bladewatch.app.grpc.v1.SunroofStatusOrBuilder getSunroofOrBuilder();

  /**
   * <code>.bladewatch.v1.BatteryStatus battery = 7 [json_name = "battery"];</code>
   * @return Whether the battery field is set.
   */
  boolean hasBattery();
  /**
   * <code>.bladewatch.v1.BatteryStatus battery = 7 [json_name = "battery"];</code>
   * @return The battery.
   */
  net.bladewatch.app.grpc.v1.BatteryStatus getBattery();
  /**
   * <code>.bladewatch.v1.BatteryStatus battery = 7 [json_name = "battery"];</code>
   */
  net.bladewatch.app.grpc.v1.BatteryStatusOrBuilder getBatteryOrBuilder();

  /**
   * <code>.bladewatch.v1.LightStatus lights = 8 [json_name = "lights"];</code>
   * @return Whether the lights field is set.
   */
  boolean hasLights();
  /**
   * <code>.bladewatch.v1.LightStatus lights = 8 [json_name = "lights"];</code>
   * @return The lights.
   */
  net.bladewatch.app.grpc.v1.LightStatus getLights();
  /**
   * <code>.bladewatch.v1.LightStatus lights = 8 [json_name = "lights"];</code>
   */
  net.bladewatch.app.grpc.v1.LightStatusOrBuilder getLightsOrBuilder();

  /**
   * <code>.bladewatch.v1.AdasStatus adas = 9 [json_name = "adas"];</code>
   * @return Whether the adas field is set.
   */
  boolean hasAdas();
  /**
   * <code>.bladewatch.v1.AdasStatus adas = 9 [json_name = "adas"];</code>
   * @return The adas.
   */
  net.bladewatch.app.grpc.v1.AdasStatus getAdas();
  /**
   * <code>.bladewatch.v1.AdasStatus adas = 9 [json_name = "adas"];</code>
   */
  net.bladewatch.app.grpc.v1.AdasStatusOrBuilder getAdasOrBuilder();

  /**
   * <code>.bladewatch.v1.SeatStatus seats = 10 [json_name = "seats"];</code>
   * @return Whether the seats field is set.
   */
  boolean hasSeats();
  /**
   * <code>.bladewatch.v1.SeatStatus seats = 10 [json_name = "seats"];</code>
   * @return The seats.
   */
  net.bladewatch.app.grpc.v1.SeatStatus getSeats();
  /**
   * <code>.bladewatch.v1.SeatStatus seats = 10 [json_name = "seats"];</code>
   */
  net.bladewatch.app.grpc.v1.SeatStatusOrBuilder getSeatsOrBuilder();

  /**
   * <code>.bladewatch.v1.ClimateStatus climate = 11 [json_name = "climate"];</code>
   * @return Whether the climate field is set.
   */
  boolean hasClimate();
  /**
   * <code>.bladewatch.v1.ClimateStatus climate = 11 [json_name = "climate"];</code>
   * @return The climate.
   */
  net.bladewatch.app.grpc.v1.ClimateStatus getClimate();
  /**
   * <code>.bladewatch.v1.ClimateStatus climate = 11 [json_name = "climate"];</code>
   */
  net.bladewatch.app.grpc.v1.ClimateStatusOrBuilder getClimateOrBuilder();

  /**
   * <code>.bladewatch.v1.TyreStatus tyres = 12 [json_name = "tyres"];</code>
   * @return Whether the tyres field is set.
   */
  boolean hasTyres();
  /**
   * <code>.bladewatch.v1.TyreStatus tyres = 12 [json_name = "tyres"];</code>
   * @return The tyres.
   */
  net.bladewatch.app.grpc.v1.TyreStatus getTyres();
  /**
   * <code>.bladewatch.v1.TyreStatus tyres = 12 [json_name = "tyres"];</code>
   */
  net.bladewatch.app.grpc.v1.TyreStatusOrBuilder getTyresOrBuilder();

  /**
   * <code>string error = 13 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 13 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
