// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface GpsStatusInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.GpsStatusInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double lat = 1 [json_name = "lat"];</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double lng = 2 [json_name = "lng"];</code>
   * @return The lng.
   */
  double getLng();

  /**
   * <code>double speed_kmh = 3 [json_name = "speedKmh"];</code>
   * @return The speedKmh.
   */
  double getSpeedKmh();

  /**
   * <code>bool has_location = 4 [json_name = "hasLocation"];</code>
   * @return The hasLocation.
   */
  boolean getHasLocation();
}
