// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/recordings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface ListRecordingsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.ListRecordingsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  java.util.List<net.bladewatch.app.grpc.v1.RecordingEntry> 
      getRecordingsList();
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  net.bladewatch.app.grpc.v1.RecordingEntry getRecordings(int index);
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  int getRecordingsCount();
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  java.util.List<? extends net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder> 
      getRecordingsOrBuilderList();
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder getRecordingsOrBuilder(
      int index);

  /**
   * <code>int32 total = 2 [json_name = "total"];</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <code>int32 page = 3 [json_name = "page"];</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 page_size = 4 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  int getPageSize();
}
