// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/trips.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface ListTripsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.ListTripsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .bladewatch.v1.TripSummary trips = 2 [json_name = "trips"];</code>
   */
  java.util.List<net.bladewatch.app.grpc.v1.TripSummary> 
      getTripsList();
  /**
   * <code>repeated .bladewatch.v1.TripSummary trips = 2 [json_name = "trips"];</code>
   */
  net.bladewatch.app.grpc.v1.TripSummary getTrips(int index);
  /**
   * <code>repeated .bladewatch.v1.TripSummary trips = 2 [json_name = "trips"];</code>
   */
  int getTripsCount();
  /**
   * <code>repeated .bladewatch.v1.TripSummary trips = 2 [json_name = "trips"];</code>
   */
  java.util.List<? extends net.bladewatch.app.grpc.v1.TripSummaryOrBuilder> 
      getTripsOrBuilderList();
  /**
   * <code>repeated .bladewatch.v1.TripSummary trips = 2 [json_name = "trips"];</code>
   */
  net.bladewatch.app.grpc.v1.TripSummaryOrBuilder getTripsOrBuilder(
      int index);
}
