// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/recordings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.ListRecordingsResponse}
 */
@com.google.protobuf.Generated
public final class ListRecordingsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.ListRecordingsResponse)
    ListRecordingsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "ListRecordingsResponse");
  }
  // Use ListRecordingsResponse.newBuilder() to construct.
  private ListRecordingsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListRecordingsResponse() {
    recordings_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Recordings.internal_static_bladewatch_v1_ListRecordingsResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Recordings.internal_static_bladewatch_v1_ListRecordingsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Recordings.internal_static_bladewatch_v1_ListRecordingsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.ListRecordingsResponse.class, net.bladewatch.app.grpc.v1.ListRecordingsResponse.Builder.class);
  }

  public static final int RECORDINGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<net.bladewatch.app.grpc.v1.RecordingEntry> recordings_;
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  @java.lang.Override
  public java.util.List<net.bladewatch.app.grpc.v1.RecordingEntry> getRecordingsList() {
    return recordings_;
  }
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder> 
      getRecordingsOrBuilderList() {
    return recordings_;
  }
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  @java.lang.Override
  public int getRecordingsCount() {
    return recordings_.size();
  }
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.RecordingEntry getRecordings(int index) {
    return recordings_.get(index);
  }
  /**
   * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder getRecordingsOrBuilder(
      int index) {
    return recordings_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private int total_ = 0;
  /**
   * <code>int32 total = 2 [json_name = "total"];</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  public static final int PAGE_FIELD_NUMBER = 3;
  private int page_ = 0;
  /**
   * <code>int32 page = 3 [json_name = "page"];</code>
   * @return The page.
   */
  @java.lang.Override
  public int getPage() {
    return page_;
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 4;
  private int pageSize_ = 0;
  /**
   * <code>int32 page_size = 4 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recordings_.size(); i++) {
      output.writeMessage(1, recordings_.get(i));
    }
    if (total_ != 0) {
      output.writeInt32(2, total_);
    }
    if (page_ != 0) {
      output.writeInt32(3, page_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(4, pageSize_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = recordings_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(recordings_.get(i));
          }
          size += 1 * count;
        }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, total_);
    }
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, page_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, pageSize_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.ListRecordingsResponse)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.ListRecordingsResponse other = (net.bladewatch.app.grpc.v1.ListRecordingsResponse) obj;

    if (!getRecordingsList()
        .equals(other.getRecordingsList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (getPage()
        != other.getPage()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecordingsCount() > 0) {
      hash = (37 * hash) + RECORDINGS_FIELD_NUMBER;
      hash = (53 * hash) + getRecordingsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.ListRecordingsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.ListRecordingsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.ListRecordingsResponse)
      net.bladewatch.app.grpc.v1.ListRecordingsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Recordings.internal_static_bladewatch_v1_ListRecordingsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Recordings.internal_static_bladewatch_v1_ListRecordingsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.ListRecordingsResponse.class, net.bladewatch.app.grpc.v1.ListRecordingsResponse.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.ListRecordingsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (recordingsBuilder_ == null) {
        recordings_ = java.util.Collections.emptyList();
      } else {
        recordings_ = null;
        recordingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = 0;
      page_ = 0;
      pageSize_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Recordings.internal_static_bladewatch_v1_ListRecordingsResponse_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ListRecordingsResponse getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.ListRecordingsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ListRecordingsResponse build() {
      net.bladewatch.app.grpc.v1.ListRecordingsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ListRecordingsResponse buildPartial() {
      net.bladewatch.app.grpc.v1.ListRecordingsResponse result = new net.bladewatch.app.grpc.v1.ListRecordingsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(net.bladewatch.app.grpc.v1.ListRecordingsResponse result) {
      if (recordingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          recordings_ = java.util.Collections.unmodifiableList(recordings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recordings_ = recordings_;
      } else {
        result.recordings_ = recordingsBuilder_.build();
      }
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.ListRecordingsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.total_ = total_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.page_ = page_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pageSize_ = pageSize_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.ListRecordingsResponse) {
        return mergeFrom((net.bladewatch.app.grpc.v1.ListRecordingsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.ListRecordingsResponse other) {
      if (other == net.bladewatch.app.grpc.v1.ListRecordingsResponse.getDefaultInstance()) return this;
      if (recordingsBuilder_ == null) {
        if (!other.recordings_.isEmpty()) {
          if (recordings_.isEmpty()) {
            recordings_ = other.recordings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecordingsIsMutable();
            recordings_.addAll(other.recordings_);
          }
          onChanged();
        }
      } else {
        if (!other.recordings_.isEmpty()) {
          if (recordingsBuilder_.isEmpty()) {
            recordingsBuilder_.dispose();
            recordingsBuilder_ = null;
            recordings_ = other.recordings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recordingsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRecordingsFieldBuilder() : null;
          } else {
            recordingsBuilder_.addAllMessages(other.recordings_);
          }
        }
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              net.bladewatch.app.grpc.v1.RecordingEntry m =
                  input.readMessage(
                      net.bladewatch.app.grpc.v1.RecordingEntry.parser(),
                      extensionRegistry);
              if (recordingsBuilder_ == null) {
                ensureRecordingsIsMutable();
                recordings_.add(m);
              } else {
                recordingsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              page_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              pageSize_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<net.bladewatch.app.grpc.v1.RecordingEntry> recordings_ =
      java.util.Collections.emptyList();
    private void ensureRecordingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        recordings_ = new java.util.ArrayList<net.bladewatch.app.grpc.v1.RecordingEntry>(recordings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        net.bladewatch.app.grpc.v1.RecordingEntry, net.bladewatch.app.grpc.v1.RecordingEntry.Builder, net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder> recordingsBuilder_;

    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public java.util.List<net.bladewatch.app.grpc.v1.RecordingEntry> getRecordingsList() {
      if (recordingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recordings_);
      } else {
        return recordingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public int getRecordingsCount() {
      if (recordingsBuilder_ == null) {
        return recordings_.size();
      } else {
        return recordingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public net.bladewatch.app.grpc.v1.RecordingEntry getRecordings(int index) {
      if (recordingsBuilder_ == null) {
        return recordings_.get(index);
      } else {
        return recordingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder setRecordings(
        int index, net.bladewatch.app.grpc.v1.RecordingEntry value) {
      if (recordingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordingsIsMutable();
        recordings_.set(index, value);
        onChanged();
      } else {
        recordingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder setRecordings(
        int index, net.bladewatch.app.grpc.v1.RecordingEntry.Builder builderForValue) {
      if (recordingsBuilder_ == null) {
        ensureRecordingsIsMutable();
        recordings_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder addRecordings(net.bladewatch.app.grpc.v1.RecordingEntry value) {
      if (recordingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordingsIsMutable();
        recordings_.add(value);
        onChanged();
      } else {
        recordingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder addRecordings(
        int index, net.bladewatch.app.grpc.v1.RecordingEntry value) {
      if (recordingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordingsIsMutable();
        recordings_.add(index, value);
        onChanged();
      } else {
        recordingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder addRecordings(
        net.bladewatch.app.grpc.v1.RecordingEntry.Builder builderForValue) {
      if (recordingsBuilder_ == null) {
        ensureRecordingsIsMutable();
        recordings_.add(builderForValue.build());
        onChanged();
      } else {
        recordingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder addRecordings(
        int index, net.bladewatch.app.grpc.v1.RecordingEntry.Builder builderForValue) {
      if (recordingsBuilder_ == null) {
        ensureRecordingsIsMutable();
        recordings_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder addAllRecordings(
        java.lang.Iterable<? extends net.bladewatch.app.grpc.v1.RecordingEntry> values) {
      if (recordingsBuilder_ == null) {
        ensureRecordingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recordings_);
        onChanged();
      } else {
        recordingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder clearRecordings() {
      if (recordingsBuilder_ == null) {
        recordings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recordingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public Builder removeRecordings(int index) {
      if (recordingsBuilder_ == null) {
        ensureRecordingsIsMutable();
        recordings_.remove(index);
        onChanged();
      } else {
        recordingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public net.bladewatch.app.grpc.v1.RecordingEntry.Builder getRecordingsBuilder(
        int index) {
      return internalGetRecordingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder getRecordingsOrBuilder(
        int index) {
      if (recordingsBuilder_ == null) {
        return recordings_.get(index);  } else {
        return recordingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public java.util.List<? extends net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder> 
         getRecordingsOrBuilderList() {
      if (recordingsBuilder_ != null) {
        return recordingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recordings_);
      }
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public net.bladewatch.app.grpc.v1.RecordingEntry.Builder addRecordingsBuilder() {
      return internalGetRecordingsFieldBuilder().addBuilder(
          net.bladewatch.app.grpc.v1.RecordingEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public net.bladewatch.app.grpc.v1.RecordingEntry.Builder addRecordingsBuilder(
        int index) {
      return internalGetRecordingsFieldBuilder().addBuilder(
          index, net.bladewatch.app.grpc.v1.RecordingEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .bladewatch.v1.RecordingEntry recordings = 1 [json_name = "recordings"];</code>
     */
    public java.util.List<net.bladewatch.app.grpc.v1.RecordingEntry.Builder> 
         getRecordingsBuilderList() {
      return internalGetRecordingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        net.bladewatch.app.grpc.v1.RecordingEntry, net.bladewatch.app.grpc.v1.RecordingEntry.Builder, net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder> 
        internalGetRecordingsFieldBuilder() {
      if (recordingsBuilder_ == null) {
        recordingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            net.bladewatch.app.grpc.v1.RecordingEntry, net.bladewatch.app.grpc.v1.RecordingEntry.Builder, net.bladewatch.app.grpc.v1.RecordingEntryOrBuilder>(
                recordings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        recordings_ = null;
      }
      return recordingsBuilder_;
    }

    private int total_ ;
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 2 [json_name = "total"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000002);
      total_ = 0;
      onChanged();
      return this;
    }

    private int page_ ;
    /**
     * <code>int32 page = 3 [json_name = "page"];</code>
     * @return The page.
     */
    @java.lang.Override
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 3 [json_name = "page"];</code>
     * @param value The page to set.
     * @return This builder for chaining.
     */
    public Builder setPage(int value) {

      page_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 3 [json_name = "page"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 page_size = 4 [json_name = "pageSize"];</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 page_size = 4 [json_name = "pageSize"];</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {

      pageSize_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page_size = 4 [json_name = "pageSize"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      pageSize_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.ListRecordingsResponse)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.ListRecordingsResponse)
  private static final net.bladewatch.app.grpc.v1.ListRecordingsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.ListRecordingsResponse();
  }

  public static net.bladewatch.app.grpc.v1.ListRecordingsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListRecordingsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListRecordingsResponse>() {
    @java.lang.Override
    public ListRecordingsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListRecordingsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListRecordingsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.ListRecordingsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

