// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/notifications.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.ListSubscriptionsResponse}
 */
@com.google.protobuf.Generated
public final class ListSubscriptionsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.ListSubscriptionsResponse)
    ListSubscriptionsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "ListSubscriptionsResponse");
  }
  // Use ListSubscriptionsResponse.newBuilder() to construct.
  private ListSubscriptionsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListSubscriptionsResponse() {
    subscriptions_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_ListSubscriptionsResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_ListSubscriptionsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_ListSubscriptionsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.ListSubscriptionsResponse.class, net.bladewatch.app.grpc.v1.ListSubscriptionsResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int SUBSCRIPTIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<net.bladewatch.app.grpc.v1.PushSubscriptionRecord> subscriptions_;
  /**
   * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
   */
  @java.lang.Override
  public java.util.List<net.bladewatch.app.grpc.v1.PushSubscriptionRecord> getSubscriptionsList() {
    return subscriptions_;
  }
  /**
   * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.bladewatch.app.grpc.v1.PushSubscriptionRecordOrBuilder> 
      getSubscriptionsOrBuilderList() {
    return subscriptions_;
  }
  /**
   * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
   */
  @java.lang.Override
  public int getSubscriptionsCount() {
    return subscriptions_.size();
  }
  /**
   * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.PushSubscriptionRecord getSubscriptions(int index) {
    return subscriptions_.get(index);
  }
  /**
   * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
   */
  @java.lang.Override
  public net.bladewatch.app.grpc.v1.PushSubscriptionRecordOrBuilder getSubscriptionsOrBuilder(
      int index) {
    return subscriptions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    for (int i = 0; i < subscriptions_.size(); i++) {
      output.writeMessage(2, subscriptions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }

        {
          final int count = subscriptions_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(subscriptions_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.ListSubscriptionsResponse)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.ListSubscriptionsResponse other = (net.bladewatch.app.grpc.v1.ListSubscriptionsResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getSubscriptionsList()
        .equals(other.getSubscriptionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (getSubscriptionsCount() > 0) {
      hash = (37 * hash) + SUBSCRIPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriptionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.ListSubscriptionsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.ListSubscriptionsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.ListSubscriptionsResponse)
      net.bladewatch.app.grpc.v1.ListSubscriptionsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_ListSubscriptionsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_ListSubscriptionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.ListSubscriptionsResponse.class, net.bladewatch.app.grpc.v1.ListSubscriptionsResponse.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.ListSubscriptionsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      if (subscriptionsBuilder_ == null) {
        subscriptions_ = java.util.Collections.emptyList();
      } else {
        subscriptions_ = null;
        subscriptionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Notifications.internal_static_bladewatch_v1_ListSubscriptionsResponse_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ListSubscriptionsResponse getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.ListSubscriptionsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ListSubscriptionsResponse build() {
      net.bladewatch.app.grpc.v1.ListSubscriptionsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ListSubscriptionsResponse buildPartial() {
      net.bladewatch.app.grpc.v1.ListSubscriptionsResponse result = new net.bladewatch.app.grpc.v1.ListSubscriptionsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(net.bladewatch.app.grpc.v1.ListSubscriptionsResponse result) {
      if (subscriptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          subscriptions_ = java.util.Collections.unmodifiableList(subscriptions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.subscriptions_ = subscriptions_;
      } else {
        result.subscriptions_ = subscriptionsBuilder_.build();
      }
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.ListSubscriptionsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.ListSubscriptionsResponse) {
        return mergeFrom((net.bladewatch.app.grpc.v1.ListSubscriptionsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.ListSubscriptionsResponse other) {
      if (other == net.bladewatch.app.grpc.v1.ListSubscriptionsResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (subscriptionsBuilder_ == null) {
        if (!other.subscriptions_.isEmpty()) {
          if (subscriptions_.isEmpty()) {
            subscriptions_ = other.subscriptions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSubscriptionsIsMutable();
            subscriptions_.addAll(other.subscriptions_);
          }
          onChanged();
        }
      } else {
        if (!other.subscriptions_.isEmpty()) {
          if (subscriptionsBuilder_.isEmpty()) {
            subscriptionsBuilder_.dispose();
            subscriptionsBuilder_ = null;
            subscriptions_ = other.subscriptions_;
            bitField0_ = (bitField0_ & ~0x00000002);
            subscriptionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSubscriptionsFieldBuilder() : null;
          } else {
            subscriptionsBuilder_.addAllMessages(other.subscriptions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              net.bladewatch.app.grpc.v1.PushSubscriptionRecord m =
                  input.readMessage(
                      net.bladewatch.app.grpc.v1.PushSubscriptionRecord.parser(),
                      extensionRegistry);
              if (subscriptionsBuilder_ == null) {
                ensureSubscriptionsIsMutable();
                subscriptions_.add(m);
              } else {
                subscriptionsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.util.List<net.bladewatch.app.grpc.v1.PushSubscriptionRecord> subscriptions_ =
      java.util.Collections.emptyList();
    private void ensureSubscriptionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        subscriptions_ = new java.util.ArrayList<net.bladewatch.app.grpc.v1.PushSubscriptionRecord>(subscriptions_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        net.bladewatch.app.grpc.v1.PushSubscriptionRecord, net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder, net.bladewatch.app.grpc.v1.PushSubscriptionRecordOrBuilder> subscriptionsBuilder_;

    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public java.util.List<net.bladewatch.app.grpc.v1.PushSubscriptionRecord> getSubscriptionsList() {
      if (subscriptionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subscriptions_);
      } else {
        return subscriptionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public int getSubscriptionsCount() {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.size();
      } else {
        return subscriptionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public net.bladewatch.app.grpc.v1.PushSubscriptionRecord getSubscriptions(int index) {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.get(index);
      } else {
        return subscriptionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder setSubscriptions(
        int index, net.bladewatch.app.grpc.v1.PushSubscriptionRecord value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.set(index, value);
        onChanged();
      } else {
        subscriptionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder setSubscriptions(
        int index, net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.set(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder addSubscriptions(net.bladewatch.app.grpc.v1.PushSubscriptionRecord value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.add(value);
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder addSubscriptions(
        int index, net.bladewatch.app.grpc.v1.PushSubscriptionRecord value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.add(index, value);
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder addSubscriptions(
        net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.add(builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder addSubscriptions(
        int index, net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.add(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder addAllSubscriptions(
        java.lang.Iterable<? extends net.bladewatch.app.grpc.v1.PushSubscriptionRecord> values) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subscriptions_);
        onChanged();
      } else {
        subscriptionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder clearSubscriptions() {
      if (subscriptionsBuilder_ == null) {
        subscriptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        subscriptionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public Builder removeSubscriptions(int index) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.remove(index);
        onChanged();
      } else {
        subscriptionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder getSubscriptionsBuilder(
        int index) {
      return internalGetSubscriptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public net.bladewatch.app.grpc.v1.PushSubscriptionRecordOrBuilder getSubscriptionsOrBuilder(
        int index) {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.get(index);  } else {
        return subscriptionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public java.util.List<? extends net.bladewatch.app.grpc.v1.PushSubscriptionRecordOrBuilder> 
         getSubscriptionsOrBuilderList() {
      if (subscriptionsBuilder_ != null) {
        return subscriptionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subscriptions_);
      }
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder addSubscriptionsBuilder() {
      return internalGetSubscriptionsFieldBuilder().addBuilder(
          net.bladewatch.app.grpc.v1.PushSubscriptionRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder addSubscriptionsBuilder(
        int index) {
      return internalGetSubscriptionsFieldBuilder().addBuilder(
          index, net.bladewatch.app.grpc.v1.PushSubscriptionRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .bladewatch.v1.PushSubscriptionRecord subscriptions = 2 [json_name = "subscriptions"];</code>
     */
    public java.util.List<net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder> 
         getSubscriptionsBuilderList() {
      return internalGetSubscriptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        net.bladewatch.app.grpc.v1.PushSubscriptionRecord, net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder, net.bladewatch.app.grpc.v1.PushSubscriptionRecordOrBuilder> 
        internalGetSubscriptionsFieldBuilder() {
      if (subscriptionsBuilder_ == null) {
        subscriptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            net.bladewatch.app.grpc.v1.PushSubscriptionRecord, net.bladewatch.app.grpc.v1.PushSubscriptionRecord.Builder, net.bladewatch.app.grpc.v1.PushSubscriptionRecordOrBuilder>(
                subscriptions_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        subscriptions_ = null;
      }
      return subscriptionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.ListSubscriptionsResponse)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.ListSubscriptionsResponse)
  private static final net.bladewatch.app.grpc.v1.ListSubscriptionsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.ListSubscriptionsResponse();
  }

  public static net.bladewatch.app.grpc.v1.ListSubscriptionsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListSubscriptionsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListSubscriptionsResponse>() {
    @java.lang.Override
    public ListSubscriptionsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListSubscriptionsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListSubscriptionsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.ListSubscriptionsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

