// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: bladewatch/v1/notifications.proto
//
package net.bladewatch.app.grpc.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  NotificationsService manages Web Push subscriptions and notification preferences.
 *
 *  HTTP mapping:
 *    GetCategories        GET  /api/notifications/categories
 *    Subscribe            POST /api/push/subscribe
 *    Unsubscribe          POST /api/push/unsubscribe
 *    ListSubscriptions    GET  /api/push/subscriptions
 *    UpdatePreferences    POST /api/push/preferences
 *    SendTest             POST /api/push/test
 */
public interface NotificationsServiceClientInterface {
  public suspend fun getCategories(request: GetCategoriesRequest, headers: Headers = emptyMap()): ResponseMessage<GetCategoriesResponse>

  public suspend fun subscribe(request: SubscribeRequest, headers: Headers = emptyMap()): ResponseMessage<SubscribeResponse>

  public suspend fun unsubscribe(request: UnsubscribeRequest, headers: Headers = emptyMap()): ResponseMessage<UnsubscribeResponse>

  public suspend fun listSubscriptions(request: ListSubscriptionsRequest, headers: Headers = emptyMap()): ResponseMessage<ListSubscriptionsResponse>

  public suspend fun updatePreferences(request: UpdatePreferencesRequest, headers: Headers = emptyMap()): ResponseMessage<UpdatePreferencesResponse>

  public suspend fun sendTest(request: SendTestRequest, headers: Headers = emptyMap()): ResponseMessage<SendTestResponse>
}
