// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface PreviewCleanupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.PreviewCleanupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional target bytes to free for the preview. 0 = use the handler default (500 MB).
   * Passed to the REST handler as the ?bytesToFree= query param.
   * </pre>
   *
   * <code>int64 bytes_to_free = 1 [json_name = "bytesToFree"];</code>
   * @return The bytesToFree.
   */
  long getBytesToFree();
}
