// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface PreviewCleanupFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.PreviewCleanupFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>int64 size_bytes = 2 [json_name = "size"];</code>
   * @return The sizeBytes.
   */
  long getSizeBytes();
}
