// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface PreviewCleanupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.PreviewCleanupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .bladewatch.v1.PreviewCleanupFile files = 2 [json_name = "files"];</code>
   */
  java.util.List<net.bladewatch.app.grpc.v1.PreviewCleanupFile> 
      getFilesList();
  /**
   * <code>repeated .bladewatch.v1.PreviewCleanupFile files = 2 [json_name = "files"];</code>
   */
  net.bladewatch.app.grpc.v1.PreviewCleanupFile getFiles(int index);
  /**
   * <code>repeated .bladewatch.v1.PreviewCleanupFile files = 2 [json_name = "files"];</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .bladewatch.v1.PreviewCleanupFile files = 2 [json_name = "files"];</code>
   */
  java.util.List<? extends net.bladewatch.app.grpc.v1.PreviewCleanupFileOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .bladewatch.v1.PreviewCleanupFile files = 2 [json_name = "files"];</code>
   */
  net.bladewatch.app.grpc.v1.PreviewCleanupFileOrBuilder getFilesOrBuilder(
      int index);

  /**
   * <code>int64 total_deletable_bytes = 3 [json_name = "totalDeletableBytes"];</code>
   * @return The totalDeletableBytes.
   */
  long getTotalDeletableBytes();

  /**
   * <code>int32 total_deletable_count = 4 [json_name = "totalDeletableCount"];</code>
   * @return The totalDeletableCount.
   */
  int getTotalDeletableCount();
}
