// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * RecordingQualityTier identifies a named recording quality preset.
 * </pre>
 *
 * Protobuf enum {@code bladewatch.v1.RecordingQualityTier}
 */
@com.google.protobuf.Generated
public enum RecordingQualityTier
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RECORDING_QUALITY_TIER_UNSPECIFIED = 0;</code>
   */
  RECORDING_QUALITY_TIER_UNSPECIFIED(0),
  /**
   * <code>RECORDING_QUALITY_TIER_ECONOMY = 1;</code>
   */
  RECORDING_QUALITY_TIER_ECONOMY(1),
  /**
   * <code>RECORDING_QUALITY_TIER_STANDARD = 2;</code>
   */
  RECORDING_QUALITY_TIER_STANDARD(2),
  /**
   * <code>RECORDING_QUALITY_TIER_HIGH = 3;</code>
   */
  RECORDING_QUALITY_TIER_HIGH(3),
  /**
   * <code>RECORDING_QUALITY_TIER_PREMIUM = 4;</code>
   */
  RECORDING_QUALITY_TIER_PREMIUM(4),
  /**
   * <code>RECORDING_QUALITY_TIER_MAX = 5;</code>
   */
  RECORDING_QUALITY_TIER_MAX(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "RecordingQualityTier");
  }
  /**
   * <code>RECORDING_QUALITY_TIER_UNSPECIFIED = 0;</code>
   */
  public static final int RECORDING_QUALITY_TIER_UNSPECIFIED_VALUE = 0;
  /**
   * <code>RECORDING_QUALITY_TIER_ECONOMY = 1;</code>
   */
  public static final int RECORDING_QUALITY_TIER_ECONOMY_VALUE = 1;
  /**
   * <code>RECORDING_QUALITY_TIER_STANDARD = 2;</code>
   */
  public static final int RECORDING_QUALITY_TIER_STANDARD_VALUE = 2;
  /**
   * <code>RECORDING_QUALITY_TIER_HIGH = 3;</code>
   */
  public static final int RECORDING_QUALITY_TIER_HIGH_VALUE = 3;
  /**
   * <code>RECORDING_QUALITY_TIER_PREMIUM = 4;</code>
   */
  public static final int RECORDING_QUALITY_TIER_PREMIUM_VALUE = 4;
  /**
   * <code>RECORDING_QUALITY_TIER_MAX = 5;</code>
   */
  public static final int RECORDING_QUALITY_TIER_MAX_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RecordingQualityTier valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RecordingQualityTier forNumber(int value) {
    switch (value) {
      case 0: return RECORDING_QUALITY_TIER_UNSPECIFIED;
      case 1: return RECORDING_QUALITY_TIER_ECONOMY;
      case 2: return RECORDING_QUALITY_TIER_STANDARD;
      case 3: return RECORDING_QUALITY_TIER_HIGH;
      case 4: return RECORDING_QUALITY_TIER_PREMIUM;
      case 5: return RECORDING_QUALITY_TIER_MAX;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RecordingQualityTier>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RecordingQualityTier> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RecordingQualityTier>() {
          public RecordingQualityTier findValueByNumber(int number) {
            return RecordingQualityTier.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Settings.getDescriptor().getEnumType(0);
  }

  private static final RecordingQualityTier[] VALUES = values();

  public static RecordingQualityTier valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RecordingQualityTier(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bladewatch.v1.RecordingQualityTier)
}

