// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.ResetPerformanceResponse}
 */
@com.google.protobuf.Generated
public final class ResetPerformanceResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.ResetPerformanceResponse)
    ResetPerformanceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "ResetPerformanceResponse");
  }
  // Use ResetPerformanceResponse.newBuilder() to construct.
  private ResetPerformanceResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResetPerformanceResponse() {
    resultsJson_ = "";
    error_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_ResetPerformanceResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_ResetPerformanceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_ResetPerformanceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.ResetPerformanceResponse.class, net.bladewatch.app.grpc.v1.ResetPerformanceResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int RESULTS_JSON_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resultsJson_ = "";
  /**
   * <pre>
   * Per-category result objects encoded as JSON (map serialisation complexity avoided).
   * </pre>
   *
   * <code>string results_json = 2 [json_name = "resultsJson"];</code>
   * @return The resultsJson.
   */
  @java.lang.Override
  public java.lang.String getResultsJson() {
    java.lang.Object ref = resultsJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultsJson_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Per-category result objects encoded as JSON (map serialisation complexity avoided).
   * </pre>
   *
   * <code>string results_json = 2 [json_name = "resultsJson"];</code>
   * @return The bytes for resultsJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultsJsonBytes() {
    java.lang.Object ref = resultsJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultsJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resultsJson_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, resultsJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, error_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resultsJson_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, resultsJson_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, error_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.ResetPerformanceResponse)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.ResetPerformanceResponse other = (net.bladewatch.app.grpc.v1.ResetPerformanceResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getResultsJson()
        .equals(other.getResultsJson())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + RESULTS_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getResultsJson().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.ResetPerformanceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.ResetPerformanceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.ResetPerformanceResponse)
      net.bladewatch.app.grpc.v1.ResetPerformanceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_ResetPerformanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_ResetPerformanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.ResetPerformanceResponse.class, net.bladewatch.app.grpc.v1.ResetPerformanceResponse.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.ResetPerformanceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      resultsJson_ = "";
      error_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_ResetPerformanceResponse_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ResetPerformanceResponse getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.ResetPerformanceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ResetPerformanceResponse build() {
      net.bladewatch.app.grpc.v1.ResetPerformanceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.ResetPerformanceResponse buildPartial() {
      net.bladewatch.app.grpc.v1.ResetPerformanceResponse result = new net.bladewatch.app.grpc.v1.ResetPerformanceResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.ResetPerformanceResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.resultsJson_ = resultsJson_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = error_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.ResetPerformanceResponse) {
        return mergeFrom((net.bladewatch.app.grpc.v1.ResetPerformanceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.ResetPerformanceResponse other) {
      if (other == net.bladewatch.app.grpc.v1.ResetPerformanceResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getResultsJson().isEmpty()) {
        resultsJson_ = other.resultsJson_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              resultsJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object resultsJson_ = "";
    /**
     * <pre>
     * Per-category result objects encoded as JSON (map serialisation complexity avoided).
     * </pre>
     *
     * <code>string results_json = 2 [json_name = "resultsJson"];</code>
     * @return The resultsJson.
     */
    public java.lang.String getResultsJson() {
      java.lang.Object ref = resultsJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultsJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Per-category result objects encoded as JSON (map serialisation complexity avoided).
     * </pre>
     *
     * <code>string results_json = 2 [json_name = "resultsJson"];</code>
     * @return The bytes for resultsJson.
     */
    public com.google.protobuf.ByteString
        getResultsJsonBytes() {
      java.lang.Object ref = resultsJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultsJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Per-category result objects encoded as JSON (map serialisation complexity avoided).
     * </pre>
     *
     * <code>string results_json = 2 [json_name = "resultsJson"];</code>
     * @param value The resultsJson to set.
     * @return This builder for chaining.
     */
    public Builder setResultsJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resultsJson_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Per-category result objects encoded as JSON (map serialisation complexity avoided).
     * </pre>
     *
     * <code>string results_json = 2 [json_name = "resultsJson"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResultsJson() {
      resultsJson_ = getDefaultInstance().getResultsJson();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Per-category result objects encoded as JSON (map serialisation complexity avoided).
     * </pre>
     *
     * <code>string results_json = 2 [json_name = "resultsJson"];</code>
     * @param value The bytes for resultsJson to set.
     * @return This builder for chaining.
     */
    public Builder setResultsJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resultsJson_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 3 [json_name = "error"];</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 3 [json_name = "error"];</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 3 [json_name = "error"];</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 3 [json_name = "error"];</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string error = 3 [json_name = "error"];</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.ResetPerformanceResponse)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.ResetPerformanceResponse)
  private static final net.bladewatch.app.grpc.v1.ResetPerformanceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.ResetPerformanceResponse();
  }

  public static net.bladewatch.app.grpc.v1.ResetPerformanceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResetPerformanceResponse>
      PARSER = new com.google.protobuf.AbstractParser<ResetPerformanceResponse>() {
    @java.lang.Override
    public ResetPerformanceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResetPerformanceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResetPerformanceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.ResetPerformanceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

