// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: bladewatch/v1/safe_locations.proto
//
package net.bladewatch.app.grpc.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  SafeLocationsService manages geofence zones that suppress surveillance alerts.
 *
 *  HTTP mapping:
 *    ListZones    GET    /api/surveillance/safe-locations
 *    AddZone      POST   /api/surveillance/safe-locations
 *    UpdateZone   PUT    /api/surveillance/safe-locations  (id via ?id=xxx or request body)
 *    DeleteZone   DELETE /api/surveillance/safe-locations  (id via ?id=xxx or request body)
 *    Over Connect the id travels in the request body (UpdateZoneRequest.id / DeleteZoneRequest.id);
 *    the REST handler accepts either the ?id= query param or the body id.
 *    Toggle       POST   /api/surveillance/safe-locations/toggle
 */
public interface SafeLocationsServiceClientInterface {
  public suspend fun listZones(request: ListZonesRequest, headers: Headers = emptyMap()): ResponseMessage<ListZonesResponse>

  public suspend fun addZone(request: AddZoneRequest, headers: Headers = emptyMap()): ResponseMessage<AddZoneResponse>

  public suspend fun updateZone(request: UpdateZoneRequest, headers: Headers = emptyMap()): ResponseMessage<UpdateZoneResponse>

  public suspend fun deleteZone(request: DeleteZoneRequest, headers: Headers = emptyMap()): ResponseMessage<DeleteZoneResponse>

  public suspend fun toggle(request: ToggleSafeLocationsRequest, headers: Headers = emptyMap()): ResponseMessage<ToggleSafeLocationsResponse>
}
