// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/safe_locations.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SafeZoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SafeZone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double lat = 3 [json_name = "lat"];</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double lng = 4 [json_name = "lng"];</code>
   * @return The lng.
   */
  double getLng();

  /**
   * <pre>
   * Radius in metres.
   * </pre>
   *
   * <code>int32 radius_m = 5 [json_name = "radiusM"];</code>
   * @return The radiusM.
   */
  int getRadiusM();

  /**
   * <code>bool active = 6 [json_name = "enabled"];</code>
   * @return The active.
   */
  boolean getActive();

  /**
   * <pre>
   * Epoch ms when the zone was created.
   * </pre>
   *
   * <code>int64 created_at_ms = 7 [json_name = "createdAt"];</code>
   * @return The createdAtMs.
   */
  long getCreatedAtMs();
}
