// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SeatStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SeatStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Heating levels per seat index [0-2], 0=off.
   * </pre>
   *
   * <code>repeated int32 heat = 1 [json_name = "heat"];</code>
   * @return A list containing the heat.
   */
  java.util.List<java.lang.Integer> getHeatList();
  /**
   * <pre>
   * Heating levels per seat index [0-2], 0=off.
   * </pre>
   *
   * <code>repeated int32 heat = 1 [json_name = "heat"];</code>
   * @return The count of heat.
   */
  int getHeatCount();
  /**
   * <pre>
   * Heating levels per seat index [0-2], 0=off.
   * </pre>
   *
   * <code>repeated int32 heat = 1 [json_name = "heat"];</code>
   * @param index The index of the element to return.
   * @return The heat at the given index.
   */
  int getHeat(int index);

  /**
   * <pre>
   * Cooling levels per seat index [0-2], 0=off.
   * </pre>
   *
   * <code>repeated int32 cool = 2 [json_name = "cool"];</code>
   * @return A list containing the cool.
   */
  java.util.List<java.lang.Integer> getCoolList();
  /**
   * <pre>
   * Cooling levels per seat index [0-2], 0=off.
   * </pre>
   *
   * <code>repeated int32 cool = 2 [json_name = "cool"];</code>
   * @return The count of cool.
   */
  int getCoolCount();
  /**
   * <pre>
   * Cooling levels per seat index [0-2], 0=off.
   * </pre>
   *
   * <code>repeated int32 cool = 2 [json_name = "cool"];</code>
   * @param index The index of the element to return.
   * @return The cool at the given index.
   */
  int getCool(int index);

  /**
   * <code>bool ventilated_supported = 3 [json_name = "ventilatedSupported"];</code>
   * @return The ventilatedSupported.
   */
  boolean getVentilatedSupported();
}
