// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetChargeCapRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetChargeCapRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 percent = 1 [json_name = "percent"];</code>
   * @return The percent.
   */
  int getPercent();

  /**
   * <code>bool enabled = 2 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();
}
