// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetClimateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetClimateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>bool on = 2 [json_name = "on"];</code>
   * @return The on.
   */
  boolean getOn();

  /**
   * <code>double setpoint_c = 3 [json_name = "setpointC"];</code>
   * @return The setpointC.
   */
  double getSetpointC();

  /**
   * <code>int32 fan_level = 4 [json_name = "fanLevel"];</code>
   * @return The fanLevel.
   */
  int getFanLevel();

  /**
   * <code>int32 wind_mode = 5 [json_name = "windMode"];</code>
   * @return The windMode.
   */
  int getWindMode();

  /**
   * <code>bool max_cooling = 6 [json_name = "maxCooling"];</code>
   * @return The maxCooling.
   */
  boolean getMaxCooling();

  /**
   * <pre>
   * Restore params: used when disabling max_cooling to re-apply prior AC state.
   * </pre>
   *
   * <code>bool restore_ac_on = 7 [json_name = "restoreAcOn"];</code>
   * @return The restoreAcOn.
   */
  boolean getRestoreAcOn();

  /**
   * <code>double restore_temp_c = 8 [json_name = "restoreTempC"];</code>
   * @return The restoreTempC.
   */
  double getRestoreTempC();

  /**
   * <code>int32 restore_fan_level = 9 [json_name = "restoreFanLevel"];</code>
   * @return The restoreFanLevel.
   */
  int getRestoreFanLevel();
}
