// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetExternalConfigResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetExternalConfigResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>bool cleanup_enabled = 2 [json_name = "cleanupEnabled"];</code>
   * @return The cleanupEnabled.
   */
  boolean getCleanupEnabled();

  /**
   * <code>int64 reserved_space_mb = 3 [json_name = "reservedSpaceMb"];</code>
   * @return The reservedSpaceMb.
   */
  long getReservedSpaceMb();

  /**
   * <code>int32 protected_hours = 4 [json_name = "protectedHours"];</code>
   * @return The protectedHours.
   */
  int getProtectedHours();

  /**
   * <code>int32 min_files_keep = 5 [json_name = "minFilesKeep"];</code>
   * @return The minFilesKeep.
   */
  int getMinFilesKeep();

  /**
   * <code>string error = 6 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 6 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
