// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/settings.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetRecordingModeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetRecordingModeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Recording mode, e.g. "CONTINUOUS", "EVENTS", "OFF".
   * </pre>
   *
   * <code>string mode = 1 [json_name = "mode"];</code>
   * @return The mode.
   */
  java.lang.String getMode();
  /**
   * <pre>
   * Recording mode, e.g. "CONTINUOUS", "EVENTS", "OFF".
   * </pre>
   *
   * <code>string mode = 1 [json_name = "mode"];</code>
   * @return The bytes for mode.
   */
  com.google.protobuf.ByteString
      getModeBytes();
}
