// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetSeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetSeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Seat index: 1=driver, 2=passenger.
   * </pre>
   *
   * <code>int32 seat_index = 1 [json_name = "seatIndex"];</code>
   * @return The seatIndex.
   */
  int getSeatIndex();

  /**
   * <code>string action = 2 [json_name = "action"];</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2 [json_name = "action"];</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>int32 level = 3 [json_name = "level"];</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * Full current seat state: cloud API is stateful and requires these on every call.
   * </pre>
   *
   * <code>int32 driver_heat = 4 [json_name = "driverHeat"];</code>
   * @return The driverHeat.
   */
  int getDriverHeat();

  /**
   * <code>int32 driver_vent = 5 [json_name = "driverVent"];</code>
   * @return The driverVent.
   */
  int getDriverVent();

  /**
   * <code>int32 passenger_heat = 6 [json_name = "passengerHeat"];</code>
   * @return The passengerHeat.
   */
  int getPassengerHeat();

  /**
   * <code>int32 passenger_vent = 7 [json_name = "passengerVent"];</code>
   * @return The passengerVent.
   */
  int getPassengerVent();
}
