// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * Protobuf type {@code bladewatch.v1.SetStorageSettingsRequest}
 */
@com.google.protobuf.Generated
public final class SetStorageSettingsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.SetStorageSettingsRequest)
    SetStorageSettingsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "SetStorageSettingsRequest");
  }
  // Use SetStorageSettingsRequest.newBuilder() to construct.
  private SetStorageSettingsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SetStorageSettingsRequest() {
    recordingsStorageType_ = "";
    surveillanceStorageType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_SetStorageSettingsRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_SetStorageSettingsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_SetStorageSettingsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.SetStorageSettingsRequest.class, net.bladewatch.app.grpc.v1.SetStorageSettingsRequest.Builder.class);
  }

  public static final int RECORDINGS_LIMIT_MB_FIELD_NUMBER = 1;
  private long recordingsLimitMb_ = 0L;
  /**
   * <code>int64 recordings_limit_mb = 1 [json_name = "recordingsLimitMb"];</code>
   * @return The recordingsLimitMb.
   */
  @java.lang.Override
  public long getRecordingsLimitMb() {
    return recordingsLimitMb_;
  }

  public static final int SURVEILLANCE_LIMIT_MB_FIELD_NUMBER = 2;
  private long surveillanceLimitMb_ = 0L;
  /**
   * <code>int64 surveillance_limit_mb = 2 [json_name = "surveillanceLimitMb"];</code>
   * @return The surveillanceLimitMb.
   */
  @java.lang.Override
  public long getSurveillanceLimitMb() {
    return surveillanceLimitMb_;
  }

  public static final int RECORDINGS_STORAGE_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recordingsStorageType_ = "";
  /**
   * <code>string recordings_storage_type = 3 [json_name = "recordingsStorageType"];</code>
   * @return The recordingsStorageType.
   */
  @java.lang.Override
  public java.lang.String getRecordingsStorageType() {
    java.lang.Object ref = recordingsStorageType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordingsStorageType_ = s;
      return s;
    }
  }
  /**
   * <code>string recordings_storage_type = 3 [json_name = "recordingsStorageType"];</code>
   * @return The bytes for recordingsStorageType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecordingsStorageTypeBytes() {
    java.lang.Object ref = recordingsStorageType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordingsStorageType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SURVEILLANCE_STORAGE_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object surveillanceStorageType_ = "";
  /**
   * <code>string surveillance_storage_type = 4 [json_name = "surveillanceStorageType"];</code>
   * @return The surveillanceStorageType.
   */
  @java.lang.Override
  public java.lang.String getSurveillanceStorageType() {
    java.lang.Object ref = surveillanceStorageType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      surveillanceStorageType_ = s;
      return s;
    }
  }
  /**
   * <code>string surveillance_storage_type = 4 [json_name = "surveillanceStorageType"];</code>
   * @return The bytes for surveillanceStorageType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSurveillanceStorageTypeBytes() {
    java.lang.Object ref = surveillanceStorageType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      surveillanceStorageType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (recordingsLimitMb_ != 0L) {
      output.writeInt64(1, recordingsLimitMb_);
    }
    if (surveillanceLimitMb_ != 0L) {
      output.writeInt64(2, surveillanceLimitMb_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recordingsStorageType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, recordingsStorageType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(surveillanceStorageType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, surveillanceStorageType_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (recordingsLimitMb_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, recordingsLimitMb_);
    }
    if (surveillanceLimitMb_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, surveillanceLimitMb_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(recordingsStorageType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, recordingsStorageType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(surveillanceStorageType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, surveillanceStorageType_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.SetStorageSettingsRequest)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.SetStorageSettingsRequest other = (net.bladewatch.app.grpc.v1.SetStorageSettingsRequest) obj;

    if (getRecordingsLimitMb()
        != other.getRecordingsLimitMb()) return false;
    if (getSurveillanceLimitMb()
        != other.getSurveillanceLimitMb()) return false;
    if (!getRecordingsStorageType()
        .equals(other.getRecordingsStorageType())) return false;
    if (!getSurveillanceStorageType()
        .equals(other.getSurveillanceStorageType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECORDINGS_LIMIT_MB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRecordingsLimitMb());
    hash = (37 * hash) + SURVEILLANCE_LIMIT_MB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSurveillanceLimitMb());
    hash = (37 * hash) + RECORDINGS_STORAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRecordingsStorageType().hashCode();
    hash = (37 * hash) + SURVEILLANCE_STORAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSurveillanceStorageType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.SetStorageSettingsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bladewatch.v1.SetStorageSettingsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.SetStorageSettingsRequest)
      net.bladewatch.app.grpc.v1.SetStorageSettingsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_SetStorageSettingsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_SetStorageSettingsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.SetStorageSettingsRequest.class, net.bladewatch.app.grpc.v1.SetStorageSettingsRequest.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.SetStorageSettingsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recordingsLimitMb_ = 0L;
      surveillanceLimitMb_ = 0L;
      recordingsStorageType_ = "";
      surveillanceStorageType_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.Storage.internal_static_bladewatch_v1_SetStorageSettingsRequest_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.SetStorageSettingsRequest getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.SetStorageSettingsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.SetStorageSettingsRequest build() {
      net.bladewatch.app.grpc.v1.SetStorageSettingsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.SetStorageSettingsRequest buildPartial() {
      net.bladewatch.app.grpc.v1.SetStorageSettingsRequest result = new net.bladewatch.app.grpc.v1.SetStorageSettingsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.SetStorageSettingsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.recordingsLimitMb_ = recordingsLimitMb_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.surveillanceLimitMb_ = surveillanceLimitMb_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.recordingsStorageType_ = recordingsStorageType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.surveillanceStorageType_ = surveillanceStorageType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.SetStorageSettingsRequest) {
        return mergeFrom((net.bladewatch.app.grpc.v1.SetStorageSettingsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.SetStorageSettingsRequest other) {
      if (other == net.bladewatch.app.grpc.v1.SetStorageSettingsRequest.getDefaultInstance()) return this;
      if (other.getRecordingsLimitMb() != 0L) {
        setRecordingsLimitMb(other.getRecordingsLimitMb());
      }
      if (other.getSurveillanceLimitMb() != 0L) {
        setSurveillanceLimitMb(other.getSurveillanceLimitMb());
      }
      if (!other.getRecordingsStorageType().isEmpty()) {
        recordingsStorageType_ = other.recordingsStorageType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSurveillanceStorageType().isEmpty()) {
        surveillanceStorageType_ = other.surveillanceStorageType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              recordingsLimitMb_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              surveillanceLimitMb_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              recordingsStorageType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              surveillanceStorageType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long recordingsLimitMb_ ;
    /**
     * <code>int64 recordings_limit_mb = 1 [json_name = "recordingsLimitMb"];</code>
     * @return The recordingsLimitMb.
     */
    @java.lang.Override
    public long getRecordingsLimitMb() {
      return recordingsLimitMb_;
    }
    /**
     * <code>int64 recordings_limit_mb = 1 [json_name = "recordingsLimitMb"];</code>
     * @param value The recordingsLimitMb to set.
     * @return This builder for chaining.
     */
    public Builder setRecordingsLimitMb(long value) {

      recordingsLimitMb_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 recordings_limit_mb = 1 [json_name = "recordingsLimitMb"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordingsLimitMb() {
      bitField0_ = (bitField0_ & ~0x00000001);
      recordingsLimitMb_ = 0L;
      onChanged();
      return this;
    }

    private long surveillanceLimitMb_ ;
    /**
     * <code>int64 surveillance_limit_mb = 2 [json_name = "surveillanceLimitMb"];</code>
     * @return The surveillanceLimitMb.
     */
    @java.lang.Override
    public long getSurveillanceLimitMb() {
      return surveillanceLimitMb_;
    }
    /**
     * <code>int64 surveillance_limit_mb = 2 [json_name = "surveillanceLimitMb"];</code>
     * @param value The surveillanceLimitMb to set.
     * @return This builder for chaining.
     */
    public Builder setSurveillanceLimitMb(long value) {

      surveillanceLimitMb_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 surveillance_limit_mb = 2 [json_name = "surveillanceLimitMb"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSurveillanceLimitMb() {
      bitField0_ = (bitField0_ & ~0x00000002);
      surveillanceLimitMb_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object recordingsStorageType_ = "";
    /**
     * <code>string recordings_storage_type = 3 [json_name = "recordingsStorageType"];</code>
     * @return The recordingsStorageType.
     */
    public java.lang.String getRecordingsStorageType() {
      java.lang.Object ref = recordingsStorageType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordingsStorageType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recordings_storage_type = 3 [json_name = "recordingsStorageType"];</code>
     * @return The bytes for recordingsStorageType.
     */
    public com.google.protobuf.ByteString
        getRecordingsStorageTypeBytes() {
      java.lang.Object ref = recordingsStorageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordingsStorageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recordings_storage_type = 3 [json_name = "recordingsStorageType"];</code>
     * @param value The recordingsStorageType to set.
     * @return This builder for chaining.
     */
    public Builder setRecordingsStorageType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recordingsStorageType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string recordings_storage_type = 3 [json_name = "recordingsStorageType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordingsStorageType() {
      recordingsStorageType_ = getDefaultInstance().getRecordingsStorageType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string recordings_storage_type = 3 [json_name = "recordingsStorageType"];</code>
     * @param value The bytes for recordingsStorageType to set.
     * @return This builder for chaining.
     */
    public Builder setRecordingsStorageTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recordingsStorageType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object surveillanceStorageType_ = "";
    /**
     * <code>string surveillance_storage_type = 4 [json_name = "surveillanceStorageType"];</code>
     * @return The surveillanceStorageType.
     */
    public java.lang.String getSurveillanceStorageType() {
      java.lang.Object ref = surveillanceStorageType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surveillanceStorageType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string surveillance_storage_type = 4 [json_name = "surveillanceStorageType"];</code>
     * @return The bytes for surveillanceStorageType.
     */
    public com.google.protobuf.ByteString
        getSurveillanceStorageTypeBytes() {
      java.lang.Object ref = surveillanceStorageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surveillanceStorageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string surveillance_storage_type = 4 [json_name = "surveillanceStorageType"];</code>
     * @param value The surveillanceStorageType to set.
     * @return This builder for chaining.
     */
    public Builder setSurveillanceStorageType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      surveillanceStorageType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string surveillance_storage_type = 4 [json_name = "surveillanceStorageType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSurveillanceStorageType() {
      surveillanceStorageType_ = getDefaultInstance().getSurveillanceStorageType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string surveillance_storage_type = 4 [json_name = "surveillanceStorageType"];</code>
     * @param value The bytes for surveillanceStorageType to set.
     * @return This builder for chaining.
     */
    public Builder setSurveillanceStorageTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      surveillanceStorageType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.SetStorageSettingsRequest)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.SetStorageSettingsRequest)
  private static final net.bladewatch.app.grpc.v1.SetStorageSettingsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.SetStorageSettingsRequest();
  }

  public static net.bladewatch.app.grpc.v1.SetStorageSettingsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetStorageSettingsRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetStorageSettingsRequest>() {
    @java.lang.Override
    public SetStorageSettingsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SetStorageSettingsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetStorageSettingsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.SetStorageSettingsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

