// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/stream.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SetViewModeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SetViewModeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 view_mode = 1 [json_name = "viewMode"];</code>
   * @return The viewMode.
   */
  int getViewMode();
}
