// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/storage.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * StorageType selects the physical storage medium.
 * </pre>
 *
 * Protobuf enum {@code bladewatch.v1.StorageType}
 */
@com.google.protobuf.Generated
public enum StorageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STORAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  STORAGE_TYPE_UNSPECIFIED(0),
  /**
   * <code>STORAGE_TYPE_INTERNAL = 1;</code>
   */
  STORAGE_TYPE_INTERNAL(1),
  /**
   * <code>STORAGE_TYPE_SD_CARD = 2;</code>
   */
  STORAGE_TYPE_SD_CARD(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "StorageType");
  }
  /**
   * <code>STORAGE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int STORAGE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>STORAGE_TYPE_INTERNAL = 1;</code>
   */
  public static final int STORAGE_TYPE_INTERNAL_VALUE = 1;
  /**
   * <code>STORAGE_TYPE_SD_CARD = 2;</code>
   */
  public static final int STORAGE_TYPE_SD_CARD_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StorageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static StorageType forNumber(int value) {
    switch (value) {
      case 0: return STORAGE_TYPE_UNSPECIFIED;
      case 1: return STORAGE_TYPE_INTERNAL;
      case 2: return STORAGE_TYPE_SD_CARD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StorageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StorageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StorageType>() {
          public StorageType findValueByNumber(int number) {
            return StorageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Storage.getDescriptor().getEnumType(0);
  }

  private static final StorageType[] VALUES = values();

  public static StorageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StorageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bladewatch.v1.StorageType)
}

