// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: bladewatch/v1/stream.proto
//
package net.bladewatch.app.grpc.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  StreamService controls the WebSocket live-view stream on port 8887.
 *
 *  HTTP mapping:
 *    Enable           POST /api/stream/enable
 *    Disable          POST /api/stream/disable
 *    GetStatus        GET  /api/stream/status
 *    GetQuality       GET  /api/stream/quality
 *    SetQuality       POST /api/stream/quality/{preset}
 *    SetViewMode      POST /api/stream/view/{mode}
 *    GetViewMode      GET  /api/stream/view
 */
public interface StreamServiceClientInterface {
  public suspend fun enable(request: EnableStreamRequest, headers: Headers = emptyMap()): ResponseMessage<EnableStreamResponse>

  public suspend fun disable(request: DisableStreamRequest, headers: Headers = emptyMap()): ResponseMessage<DisableStreamResponse>

  public suspend fun getStatus(request: GetStreamStatusRequest, headers: Headers = emptyMap()): ResponseMessage<GetStreamStatusResponse>

  public suspend fun getQuality(request: GetStreamQualityRequest, headers: Headers = emptyMap()): ResponseMessage<GetStreamQualityResponse>

  public suspend fun setQuality(request: SetStreamQualityRequest, headers: Headers = emptyMap()): ResponseMessage<SetStreamQualityResponse>

  public suspend fun setViewMode(request: SetViewModeRequest, headers: Headers = emptyMap()): ResponseMessage<SetViewModeResponse>

  public suspend fun getViewMode(request: GetViewModeRequest, headers: Headers = emptyMap()): ResponseMessage<GetViewModeResponse>
}
