// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: bladewatch/v1/surveillance.proto
//
package net.bladewatch.app.grpc.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  SurveillanceService manages the GPU-accelerated sentry/motion-detection pipeline.
 *
 *  HTTP mapping:
 *    GetConfig    GET  /api/surveillance/config
 *    SetConfig    POST /api/surveillance/config
 *    GetStatus    GET  /api/surveillance/status  (any method)
 *    Enable       POST /api/surveillance/enable
 *    Disable      POST /api/surveillance/disable
 *    GetHeatmap   GET  /api/surveillance/heatmap
 *    GetSnapshot  GET  /api/surveillance/snapshot/{quadrant}
 *    GetFilterLog GET  /api/surveillance/filterlog
 *    SyncCatalog  POST /api/surveillance/sync
 */
public class SurveillanceServiceClient(
  private val client: ProtocolClientInterface,
) : SurveillanceServiceClientInterface {
  override suspend fun getConfig(request: GetSurveillanceConfigRequest, headers: Headers): ResponseMessage<GetSurveillanceConfigResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/GetConfig",
      net.bladewatch.app.grpc.v1.GetSurveillanceConfigRequest::class,
      net.bladewatch.app.grpc.v1.GetSurveillanceConfigResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun setConfig(request: SetSurveillanceConfigRequest, headers: Headers): ResponseMessage<SetSurveillanceConfigResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/SetConfig",
      net.bladewatch.app.grpc.v1.SetSurveillanceConfigRequest::class,
      net.bladewatch.app.grpc.v1.SetSurveillanceConfigResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getStatus(request: GetSurveillanceStatusRequest, headers: Headers): ResponseMessage<GetSurveillanceStatusResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/GetStatus",
      net.bladewatch.app.grpc.v1.GetSurveillanceStatusRequest::class,
      net.bladewatch.app.grpc.v1.GetSurveillanceStatusResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun enable(request: EnableSurveillanceRequest, headers: Headers): ResponseMessage<EnableSurveillanceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/Enable",
      net.bladewatch.app.grpc.v1.EnableSurveillanceRequest::class,
      net.bladewatch.app.grpc.v1.EnableSurveillanceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun disable(request: DisableSurveillanceRequest, headers: Headers): ResponseMessage<DisableSurveillanceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/Disable",
      net.bladewatch.app.grpc.v1.DisableSurveillanceRequest::class,
      net.bladewatch.app.grpc.v1.DisableSurveillanceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getHeatmap(request: GetHeatmapRequest, headers: Headers): ResponseMessage<GetHeatmapResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/GetHeatmap",
      net.bladewatch.app.grpc.v1.GetHeatmapRequest::class,
      net.bladewatch.app.grpc.v1.GetHeatmapResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getSnapshot(request: GetSnapshotRequest, headers: Headers): ResponseMessage<GetSnapshotResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/GetSnapshot",
      net.bladewatch.app.grpc.v1.GetSnapshotRequest::class,
      net.bladewatch.app.grpc.v1.GetSnapshotResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getFilterLog(request: GetFilterLogRequest, headers: Headers): ResponseMessage<GetFilterLogResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/GetFilterLog",
      net.bladewatch.app.grpc.v1.GetFilterLogRequest::class,
      net.bladewatch.app.grpc.v1.GetFilterLogResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun syncCatalog(request: SyncSurveillanceCatalogRequest, headers: Headers): ResponseMessage<SyncSurveillanceCatalogResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "bladewatch.v1.SurveillanceService/SyncCatalog",
      net.bladewatch.app.grpc.v1.SyncSurveillanceCatalogRequest::class,
      net.bladewatch.app.grpc.v1.SyncSurveillanceCatalogResponse::class,
      StreamType.UNARY,
    ),
  )

}
