// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/surveillance.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface SyncSurveillanceCatalogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.SyncSurveillanceCatalogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>int32 added = 3 [json_name = "added"];</code>
   * @return The added.
   */
  int getAdded();

  /**
   * <code>int32 removed = 4 [json_name = "removed"];</code>
   * @return The removed.
   */
  int getRemoved();
}
