// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public final class System extends com.google.protobuf.GeneratedFile {
  private System() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "System");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_BatteryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_BatteryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ChargingInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ChargingInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SocInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SocInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_RangeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_RangeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_SohInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_SohInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_RecordingStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_RecordingStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_TripStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_TripStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_NetworkInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_NetworkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GpsStatusInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GpsStatusInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetPerformanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetPerformanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_GetPerformanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_GetPerformanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PlayAudioTestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PlayAudioTestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_PlayAudioTestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_PlayAudioTestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ModelInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ModelInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_ListModelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_ListModelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_DownloadModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_DownloadModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bladewatch_v1_DownloadModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bladewatch_v1_DownloadModelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032bladewatch/v1/system.proto\022\rbladewatch" +
      ".v1\"\201\001\n\013BatteryInfo\022\024\n\005level\030\001 \001(\005R\005leve" +
      "l\022\026\n\006status\030\002 \001(\005R\006status\022\037\n\013is_charging" +
      "\030\003 \001(\010R\nisCharging\022#\n\rstatus_string\030\004 \001(" +
      "\tR\014statusString\"\327\001\n\014ChargingInfo\022\035\n\nstat" +
      "e_name\030\001 \001(\tR\tstateName\022\026\n\006status\030\002 \001(\tR" +
      "\006status\022+\n\022charging_power_k_w\030\003 \001(\001R\017cha" +
      "rgingPowerKW\022%\n\016is_discharging\030\004 \001(\010R\ris" +
      "Discharging\022\031\n\010is_error\030\005 \001(\010R\007isError\022!" +
      "\n\014is_estimated\030\006 \001(\010R\013isEstimated\"s\n\007Soc" +
      "Info\022\030\n\007percent\030\001 \001(\001R\007percent\022\025\n\006is_low" +
      "\030\002 \001(\010R\005isLow\022\037\n\013is_critical\030\003 \001(\010R\nisCr" +
      "itical\022\026\n\006status\030\004 \001(\tR\006status\"\354\001\n\tRange" +
      "Info\022\"\n\relec_range_km\030\001 \001(\001R\013elecRangeKm" +
      "\022\"\n\rfuel_range_km\030\002 \001(\001R\013fuelRangeKm\022$\n\016" +
      "total_range_km\030\003 \001(\001R\014totalRangeKm\022\025\n\006is" +
      "_low\030\004 \001(\010R\005isLow\022\037\n\013is_critical\030\005 \001(\010R\n" +
      "isCritical\022\026\n\006status\030\006 \001(\tR\006status\022!\n\014fu" +
      "el_percent\030\007 \001(\001R\013fuelPercent\"#\n\007SohInfo" +
      "\022\030\n\007percent\030\001 \001(\001R\007percent\"\263\001\n\017Recording" +
      "Status\022\'\n\017configured_mode\030\001 \001(\tR\016configu" +
      "redMode\022!\n\014is_recording\030\002 \001(\010R\013isRecordi" +
      "ng\022)\n\020pipeline_running\030\003 \001(\010R\017pipelineRu" +
      "nning\022\022\n\004gear\030\004 \001(\tR\004gear\022\025\n\006acc_on\030\005 \001(" +
      "\010R\005accOn\"\233\001\n\nTripStatus\022\030\n\007enabled\030\001 \001(\010" +
      "R\007enabled\022\037\n\013trip_active\030\002 \001(\010R\ntripActi" +
      "ve\022&\n\017trip_start_time\030\003 \001(\003R\rtripStartTi" +
      "me\022*\n\021trip_duration_sec\030\004 \001(\003R\017tripDurat" +
      "ionSec\"\270\001\n\013NetworkInfo\022\022\n\004type\030\001 \001(\tR\004ty" +
      "pe\022\022\n\004ssid\030\002 \001(\tR\004ssid\022\016\n\002ip\030\003 \001(\tR\002ip\022(" +
      "\n\020lan_http_enabled\030\004 \001(\010R\016lanHttpEnabled" +
      "\022\033\n\thttp_bind\030\005 \001(\tR\010httpBind\022*\n\021http_mo" +
      "de_warning\030\006 \001(\tR\017httpModeWarning\"s\n\rGps" +
      "StatusInfo\022\020\n\003lat\030\001 \001(\001R\003lat\022\020\n\003lng\030\002 \001(" +
      "\001R\003lng\022\033\n\tspeed_kmh\030\003 \001(\001R\010speedKmh\022!\n\014h" +
      "as_location\030\004 \001(\010R\013hasLocation\"\022\n\020GetSta" +
      "tusRequest\"\332\007\n\021GetStatusResponse\022\033\n\tdevi" +
      "ce_id\030\001 \001(\tR\010deviceId\022,\n\022vehicle_data_re" +
      "ady\030\002 \001(\010R\020vehicleDataReady\022\037\n\013app_versi" +
      "on\030\003 \001(\tR\nappVersion\022\034\n\trecording\030\004 \003(\005R" +
      "\trecording\022\030\n\007viewing\030\005 \003(\005R\007viewing\022\026\n\006" +
      "active\030\006 \003(\005R\006active\022\034\n\tavailable\030\007 \003(\005R" +
      "\tavailable\0224\n\007battery\030\010 \001(\0132\032.bladewatch" +
      ".v1.BatteryInfoR\007battery\022\020\n\003acc\030\t \001(\010R\003a" +
      "cc\0227\n\010charging\030\n \001(\0132\033.bladewatch.v1.Cha" +
      "rgingInfoR\010charging\022(\n\003soc\030\013 \001(\0132\026.blade" +
      "watch.v1.SocInfoR\003soc\022.\n\005range\030\014 \001(\0132\030.b" +
      "ladewatch.v1.RangeInfoR\005range\022(\n\003soh\030\r \001" +
      "(\0132\026.bladewatch.v1.SohInfoR\003soh\022#\n\rdista" +
      "nce_unit\030\016 \001(\tR\014distanceUnit\022\026\n\006locale\030\017" +
      " \001(\tR\006locale\0220\n\024safe_zone_suppressed\030\020 \001" +
      "(\010R\022safeZoneSuppressed\022 \n\014in_safe_zone\030\021" +
      " \001(\010R\ninSafeZone\022$\n\016safe_zone_name\030\022 \001(\t" +
      "R\014safeZoneName\022)\n\020gpu_surveillance\030\023 \001(\010" +
      "R\017gpuSurveillance\022I\n\020recording_status\030\024 " +
      "\001(\0132\036.bladewatch.v1.RecordingStatusR\017rec" +
      "ordingStatus\022:\n\013trip_status\030\025 \001(\0132\031.blad" +
      "ewatch.v1.TripStatusR\ntripStatus\022\031\n\010gps_" +
      "json\030\026 \001(\tR\007gpsJson\0224\n\007network\030\027 \001(\0132\032.b" +
      "ladewatch.v1.NetworkInfoR\007network\022,\n\022veh" +
      "icle_data_error\030\030 \001(\tR\020vehicleDataError\"" +
      "\027\n\025GetPerformanceRequest\"]\n\026GetPerforman" +
      "ceResponse\022\030\n\007success\030\001 \001(\010R\007success\022)\n\020" +
      "performance_json\030\002 \001(\tR\017performanceJson\"" +
      "7\n\024PlayAudioTestRequest\022\037\n\013duration_ms\030\001" +
      " \001(\005R\ndurationMs\"a\n\025PlayAudioTestRespons" +
      "e\022\030\n\007success\030\001 \001(\010R\007success\022\030\n\007message\030\002" +
      " \001(\tR\007message\022\024\n\005error\030\003 \001(\tR\005error\"p\n\tM" +
      "odelInfo\022\022\n\004name\030\001 \001(\tR\004name\022\020\n\003url\030\002 \001(" +
      "\tR\003url\022\036\n\ndownloaded\030\003 \001(\010R\ndownloaded\022\035" +
      "\n\nsize_bytes\030\004 \001(\003R\tsizeBytes\"\023\n\021ListMod" +
      "elsRequest\"`\n\022ListModelsResponse\022\030\n\007succ" +
      "ess\030\001 \001(\010R\007success\0220\n\006models\030\002 \003(\0132\030.bla" +
      "dewatch.v1.ModelInfoR\006models\"<\n\024Download" +
      "ModelRequest\022\020\n\003url\030\001 \001(\tR\003url\022\022\n\004name\030\002" +
      " \001(\tR\004name\"a\n\025DownloadModelResponse\022\030\n\007s" +
      "uccess\030\001 \001(\010R\007success\022\030\n\007message\030\002 \001(\tR\007" +
      "message\022\024\n\005error\030\003 \001(\tR\005error2\311\003\n\rSystem" +
      "Service\022N\n\tGetStatus\022\037.bladewatch.v1.Get" +
      "StatusRequest\032 .bladewatch.v1.GetStatusR" +
      "esponse\022]\n\016GetPerformance\022$.bladewatch.v" +
      "1.GetPerformanceRequest\032%.bladewatch.v1." +
      "GetPerformanceResponse\022Z\n\rPlayAudioTest\022" +
      "#.bladewatch.v1.PlayAudioTestRequest\032$.b" +
      "ladewatch.v1.PlayAudioTestResponse\022Q\n\nLi" +
      "stModels\022 .bladewatch.v1.ListModelsReque" +
      "st\032!.bladewatch.v1.ListModelsResponse\022Z\n" +
      "\rDownloadModel\022#.bladewatch.v1.DownloadM" +
      "odelRequest\032$.bladewatch.v1.DownloadMode" +
      "lResponseB\036\n\032net.bladewatch.app.grpc.v1P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bladewatch_v1_BatteryInfo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_bladewatch_v1_BatteryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_BatteryInfo_descriptor,
        new java.lang.String[] { "Level", "Status", "IsCharging", "StatusString", });
    internal_static_bladewatch_v1_ChargingInfo_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_bladewatch_v1_ChargingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ChargingInfo_descriptor,
        new java.lang.String[] { "StateName", "Status", "ChargingPowerKW", "IsDischarging", "IsError", "IsEstimated", });
    internal_static_bladewatch_v1_SocInfo_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_bladewatch_v1_SocInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SocInfo_descriptor,
        new java.lang.String[] { "Percent", "IsLow", "IsCritical", "Status", });
    internal_static_bladewatch_v1_RangeInfo_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_bladewatch_v1_RangeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_RangeInfo_descriptor,
        new java.lang.String[] { "ElecRangeKm", "FuelRangeKm", "TotalRangeKm", "IsLow", "IsCritical", "Status", "FuelPercent", });
    internal_static_bladewatch_v1_SohInfo_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_bladewatch_v1_SohInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_SohInfo_descriptor,
        new java.lang.String[] { "Percent", });
    internal_static_bladewatch_v1_RecordingStatus_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_bladewatch_v1_RecordingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_RecordingStatus_descriptor,
        new java.lang.String[] { "ConfiguredMode", "IsRecording", "PipelineRunning", "Gear", "AccOn", });
    internal_static_bladewatch_v1_TripStatus_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_bladewatch_v1_TripStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_TripStatus_descriptor,
        new java.lang.String[] { "Enabled", "TripActive", "TripStartTime", "TripDurationSec", });
    internal_static_bladewatch_v1_NetworkInfo_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_bladewatch_v1_NetworkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_NetworkInfo_descriptor,
        new java.lang.String[] { "Type", "Ssid", "Ip", "LanHttpEnabled", "HttpBind", "HttpModeWarning", });
    internal_static_bladewatch_v1_GpsStatusInfo_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_bladewatch_v1_GpsStatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GpsStatusInfo_descriptor,
        new java.lang.String[] { "Lat", "Lng", "SpeedKmh", "HasLocation", });
    internal_static_bladewatch_v1_GetStatusRequest_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_bladewatch_v1_GetStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetStatusResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_bladewatch_v1_GetStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetStatusResponse_descriptor,
        new java.lang.String[] { "DeviceId", "VehicleDataReady", "AppVersion", "Recording", "Viewing", "Active", "Available", "Battery", "Acc", "Charging", "Soc", "Range", "Soh", "DistanceUnit", "Locale", "SafeZoneSuppressed", "InSafeZone", "SafeZoneName", "GpuSurveillance", "RecordingStatus", "TripStatus", "GpsJson", "Network", "VehicleDataError", });
    internal_static_bladewatch_v1_GetPerformanceRequest_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_bladewatch_v1_GetPerformanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetPerformanceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_GetPerformanceResponse_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_bladewatch_v1_GetPerformanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_GetPerformanceResponse_descriptor,
        new java.lang.String[] { "Success", "PerformanceJson", });
    internal_static_bladewatch_v1_PlayAudioTestRequest_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_bladewatch_v1_PlayAudioTestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PlayAudioTestRequest_descriptor,
        new java.lang.String[] { "DurationMs", });
    internal_static_bladewatch_v1_PlayAudioTestResponse_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_bladewatch_v1_PlayAudioTestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_PlayAudioTestResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Error", });
    internal_static_bladewatch_v1_ModelInfo_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_bladewatch_v1_ModelInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ModelInfo_descriptor,
        new java.lang.String[] { "Name", "Url", "Downloaded", "SizeBytes", });
    internal_static_bladewatch_v1_ListModelsRequest_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_bladewatch_v1_ListModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListModelsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bladewatch_v1_ListModelsResponse_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_bladewatch_v1_ListModelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_ListModelsResponse_descriptor,
        new java.lang.String[] { "Success", "Models", });
    internal_static_bladewatch_v1_DownloadModelRequest_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_bladewatch_v1_DownloadModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_DownloadModelRequest_descriptor,
        new java.lang.String[] { "Url", "Name", });
    internal_static_bladewatch_v1_DownloadModelResponse_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_bladewatch_v1_DownloadModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bladewatch_v1_DownloadModelResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Error", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
