// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/system.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * TripStatus summarises the active trip analytics state.
 * </pre>
 *
 * Protobuf type {@code bladewatch.v1.TripStatus}
 */
@com.google.protobuf.Generated
public final class TripStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bladewatch.v1.TripStatus)
    TripStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "TripStatus");
  }
  // Use TripStatus.newBuilder() to construct.
  private TripStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TripStatus() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_TripStatus_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_TripStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_TripStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.bladewatch.app.grpc.v1.TripStatus.class, net.bladewatch.app.grpc.v1.TripStatus.Builder.class);
  }

  public static final int ENABLED_FIELD_NUMBER = 1;
  private boolean enabled_ = false;
  /**
   * <code>bool enabled = 1 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }

  public static final int TRIP_ACTIVE_FIELD_NUMBER = 2;
  private boolean tripActive_ = false;
  /**
   * <code>bool trip_active = 2 [json_name = "tripActive"];</code>
   * @return The tripActive.
   */
  @java.lang.Override
  public boolean getTripActive() {
    return tripActive_;
  }

  public static final int TRIP_START_TIME_FIELD_NUMBER = 3;
  private long tripStartTime_ = 0L;
  /**
   * <pre>
   * Epoch ms when the current trip started (0 when no trip active).
   * </pre>
   *
   * <code>int64 trip_start_time = 3 [json_name = "tripStartTime"];</code>
   * @return The tripStartTime.
   */
  @java.lang.Override
  public long getTripStartTime() {
    return tripStartTime_;
  }

  public static final int TRIP_DURATION_SEC_FIELD_NUMBER = 4;
  private long tripDurationSec_ = 0L;
  /**
   * <code>int64 trip_duration_sec = 4 [json_name = "tripDurationSec"];</code>
   * @return The tripDurationSec.
   */
  @java.lang.Override
  public long getTripDurationSec() {
    return tripDurationSec_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (enabled_ != false) {
      output.writeBool(1, enabled_);
    }
    if (tripActive_ != false) {
      output.writeBool(2, tripActive_);
    }
    if (tripStartTime_ != 0L) {
      output.writeInt64(3, tripStartTime_);
    }
    if (tripDurationSec_ != 0L) {
      output.writeInt64(4, tripDurationSec_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, enabled_);
    }
    if (tripActive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, tripActive_);
    }
    if (tripStartTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, tripStartTime_);
    }
    if (tripDurationSec_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, tripDurationSec_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.bladewatch.app.grpc.v1.TripStatus)) {
      return super.equals(obj);
    }
    net.bladewatch.app.grpc.v1.TripStatus other = (net.bladewatch.app.grpc.v1.TripStatus) obj;

    if (getEnabled()
        != other.getEnabled()) return false;
    if (getTripActive()
        != other.getTripActive()) return false;
    if (getTripStartTime()
        != other.getTripStartTime()) return false;
    if (getTripDurationSec()
        != other.getTripDurationSec()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnabled());
    hash = (37 * hash) + TRIP_ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTripActive());
    hash = (37 * hash) + TRIP_START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTripStartTime());
    hash = (37 * hash) + TRIP_DURATION_SEC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTripDurationSec());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.bladewatch.app.grpc.v1.TripStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.bladewatch.app.grpc.v1.TripStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.bladewatch.app.grpc.v1.TripStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.bladewatch.app.grpc.v1.TripStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TripStatus summarises the active trip analytics state.
   * </pre>
   *
   * Protobuf type {@code bladewatch.v1.TripStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bladewatch.v1.TripStatus)
      net.bladewatch.app.grpc.v1.TripStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_TripStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_TripStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.bladewatch.app.grpc.v1.TripStatus.class, net.bladewatch.app.grpc.v1.TripStatus.Builder.class);
    }

    // Construct using net.bladewatch.app.grpc.v1.TripStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      enabled_ = false;
      tripActive_ = false;
      tripStartTime_ = 0L;
      tripDurationSec_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.bladewatch.app.grpc.v1.System.internal_static_bladewatch_v1_TripStatus_descriptor;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.TripStatus getDefaultInstanceForType() {
      return net.bladewatch.app.grpc.v1.TripStatus.getDefaultInstance();
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.TripStatus build() {
      net.bladewatch.app.grpc.v1.TripStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.bladewatch.app.grpc.v1.TripStatus buildPartial() {
      net.bladewatch.app.grpc.v1.TripStatus result = new net.bladewatch.app.grpc.v1.TripStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.bladewatch.app.grpc.v1.TripStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.enabled_ = enabled_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tripActive_ = tripActive_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tripStartTime_ = tripStartTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tripDurationSec_ = tripDurationSec_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.bladewatch.app.grpc.v1.TripStatus) {
        return mergeFrom((net.bladewatch.app.grpc.v1.TripStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.bladewatch.app.grpc.v1.TripStatus other) {
      if (other == net.bladewatch.app.grpc.v1.TripStatus.getDefaultInstance()) return this;
      if (other.getEnabled() != false) {
        setEnabled(other.getEnabled());
      }
      if (other.getTripActive() != false) {
        setTripActive(other.getTripActive());
      }
      if (other.getTripStartTime() != 0L) {
        setTripStartTime(other.getTripStartTime());
      }
      if (other.getTripDurationSec() != 0L) {
        setTripDurationSec(other.getTripDurationSec());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              enabled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              tripActive_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              tripStartTime_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              tripDurationSec_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean enabled_ ;
    /**
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {

      enabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool enabled = 1 [json_name = "enabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      enabled_ = false;
      onChanged();
      return this;
    }

    private boolean tripActive_ ;
    /**
     * <code>bool trip_active = 2 [json_name = "tripActive"];</code>
     * @return The tripActive.
     */
    @java.lang.Override
    public boolean getTripActive() {
      return tripActive_;
    }
    /**
     * <code>bool trip_active = 2 [json_name = "tripActive"];</code>
     * @param value The tripActive to set.
     * @return This builder for chaining.
     */
    public Builder setTripActive(boolean value) {

      tripActive_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool trip_active = 2 [json_name = "tripActive"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTripActive() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tripActive_ = false;
      onChanged();
      return this;
    }

    private long tripStartTime_ ;
    /**
     * <pre>
     * Epoch ms when the current trip started (0 when no trip active).
     * </pre>
     *
     * <code>int64 trip_start_time = 3 [json_name = "tripStartTime"];</code>
     * @return The tripStartTime.
     */
    @java.lang.Override
    public long getTripStartTime() {
      return tripStartTime_;
    }
    /**
     * <pre>
     * Epoch ms when the current trip started (0 when no trip active).
     * </pre>
     *
     * <code>int64 trip_start_time = 3 [json_name = "tripStartTime"];</code>
     * @param value The tripStartTime to set.
     * @return This builder for chaining.
     */
    public Builder setTripStartTime(long value) {

      tripStartTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Epoch ms when the current trip started (0 when no trip active).
     * </pre>
     *
     * <code>int64 trip_start_time = 3 [json_name = "tripStartTime"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTripStartTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tripStartTime_ = 0L;
      onChanged();
      return this;
    }

    private long tripDurationSec_ ;
    /**
     * <code>int64 trip_duration_sec = 4 [json_name = "tripDurationSec"];</code>
     * @return The tripDurationSec.
     */
    @java.lang.Override
    public long getTripDurationSec() {
      return tripDurationSec_;
    }
    /**
     * <code>int64 trip_duration_sec = 4 [json_name = "tripDurationSec"];</code>
     * @param value The tripDurationSec to set.
     * @return This builder for chaining.
     */
    public Builder setTripDurationSec(long value) {

      tripDurationSec_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 trip_duration_sec = 4 [json_name = "tripDurationSec"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTripDurationSec() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tripDurationSec_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bladewatch.v1.TripStatus)
  }

  // @@protoc_insertion_point(class_scope:bladewatch.v1.TripStatus)
  private static final net.bladewatch.app.grpc.v1.TripStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.bladewatch.app.grpc.v1.TripStatus();
  }

  public static net.bladewatch.app.grpc.v1.TripStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TripStatus>
      PARSER = new com.google.protobuf.AbstractParser<TripStatus>() {
    @java.lang.Override
    public TripStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TripStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TripStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.bladewatch.app.grpc.v1.TripStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

