// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/notifications.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface UnsubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.UnsubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Either id or endpoint must be set.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Either id or endpoint must be set.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string endpoint = 2 [json_name = "endpoint"];</code>
   * @return The endpoint.
   */
  java.lang.String getEndpoint();
  /**
   * <code>string endpoint = 2 [json_name = "endpoint"];</code>
   * @return The bytes for endpoint.
   */
  com.google.protobuf.ByteString
      getEndpointBytes();
}
