// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/update.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

/**
 * <pre>
 * UpdatePhase names the stage an in-progress install is in.
 * </pre>
 *
 * Protobuf enum {@code bladewatch.v1.UpdatePhase}
 */
@com.google.protobuf.Generated
public enum UpdatePhase
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UPDATE_PHASE_UNSPECIFIED = 0;</code>
   */
  UPDATE_PHASE_UNSPECIFIED(0),
  /**
   * <code>UPDATE_PHASE_IDLE = 1;</code>
   */
  UPDATE_PHASE_IDLE(1),
  /**
   * <code>UPDATE_PHASE_QUEUED = 2;</code>
   */
  UPDATE_PHASE_QUEUED(2),
  /**
   * <code>UPDATE_PHASE_DOWNLOADING = 3;</code>
   */
  UPDATE_PHASE_DOWNLOADING(3),
  /**
   * <code>UPDATE_PHASE_VERIFYING = 4;</code>
   */
  UPDATE_PHASE_VERIFYING(4),
  /**
   * <code>UPDATE_PHASE_STOPPING_DAEMONS = 5;</code>
   */
  UPDATE_PHASE_STOPPING_DAEMONS(5),
  /**
   * <code>UPDATE_PHASE_INSTALLING = 6;</code>
   */
  UPDATE_PHASE_INSTALLING(6),
  /**
   * <code>UPDATE_PHASE_ERROR = 7;</code>
   */
  UPDATE_PHASE_ERROR(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "UpdatePhase");
  }
  /**
   * <code>UPDATE_PHASE_UNSPECIFIED = 0;</code>
   */
  public static final int UPDATE_PHASE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>UPDATE_PHASE_IDLE = 1;</code>
   */
  public static final int UPDATE_PHASE_IDLE_VALUE = 1;
  /**
   * <code>UPDATE_PHASE_QUEUED = 2;</code>
   */
  public static final int UPDATE_PHASE_QUEUED_VALUE = 2;
  /**
   * <code>UPDATE_PHASE_DOWNLOADING = 3;</code>
   */
  public static final int UPDATE_PHASE_DOWNLOADING_VALUE = 3;
  /**
   * <code>UPDATE_PHASE_VERIFYING = 4;</code>
   */
  public static final int UPDATE_PHASE_VERIFYING_VALUE = 4;
  /**
   * <code>UPDATE_PHASE_STOPPING_DAEMONS = 5;</code>
   */
  public static final int UPDATE_PHASE_STOPPING_DAEMONS_VALUE = 5;
  /**
   * <code>UPDATE_PHASE_INSTALLING = 6;</code>
   */
  public static final int UPDATE_PHASE_INSTALLING_VALUE = 6;
  /**
   * <code>UPDATE_PHASE_ERROR = 7;</code>
   */
  public static final int UPDATE_PHASE_ERROR_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static UpdatePhase valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static UpdatePhase forNumber(int value) {
    switch (value) {
      case 0: return UPDATE_PHASE_UNSPECIFIED;
      case 1: return UPDATE_PHASE_IDLE;
      case 2: return UPDATE_PHASE_QUEUED;
      case 3: return UPDATE_PHASE_DOWNLOADING;
      case 4: return UPDATE_PHASE_VERIFYING;
      case 5: return UPDATE_PHASE_STOPPING_DAEMONS;
      case 6: return UPDATE_PHASE_INSTALLING;
      case 7: return UPDATE_PHASE_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UpdatePhase>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      UpdatePhase> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UpdatePhase>() {
          public UpdatePhase findValueByNumber(int number) {
            return UpdatePhase.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.bladewatch.app.grpc.v1.Update.getDescriptor().getEnumType(0);
  }

  private static final UpdatePhase[] VALUES = values();

  public static UpdatePhase valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private UpdatePhase(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bladewatch.v1.UpdatePhase)
}

