// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface VehicleCapabilitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.VehicleCapabilities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bladewatch.v1.WindowCapabilities windows = 1 [json_name = "windows"];</code>
   * @return Whether the windows field is set.
   */
  boolean hasWindows();
  /**
   * <code>.bladewatch.v1.WindowCapabilities windows = 1 [json_name = "windows"];</code>
   * @return The windows.
   */
  net.bladewatch.app.grpc.v1.WindowCapabilities getWindows();
  /**
   * <code>.bladewatch.v1.WindowCapabilities windows = 1 [json_name = "windows"];</code>
   */
  net.bladewatch.app.grpc.v1.WindowCapabilitiesOrBuilder getWindowsOrBuilder();

  /**
   * <code>.bladewatch.v1.SeatCapabilities seats = 2 [json_name = "seats"];</code>
   * @return Whether the seats field is set.
   */
  boolean hasSeats();
  /**
   * <code>.bladewatch.v1.SeatCapabilities seats = 2 [json_name = "seats"];</code>
   * @return The seats.
   */
  net.bladewatch.app.grpc.v1.SeatCapabilities getSeats();
  /**
   * <code>.bladewatch.v1.SeatCapabilities seats = 2 [json_name = "seats"];</code>
   */
  net.bladewatch.app.grpc.v1.SeatCapabilitiesOrBuilder getSeatsOrBuilder();
}
