// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bladewatch/v1/vehicle.proto
// Protobuf Java Version: 4.35.0

package net.bladewatch.app.grpc.v1;

@com.google.protobuf.Generated
public interface VehicleCommandResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bladewatch.v1.VehicleCommandResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <pre>
   * Routing outcome from the server (e.g. "success", "not_supported", "failed").
   * The REST handler already emits this key via routedResponse().
   * </pre>
   *
   * <code>string outcome = 4 [json_name = "outcome"];</code>
   * @return The outcome.
   */
  java.lang.String getOutcome();
  /**
   * <pre>
   * Routing outcome from the server (e.g. "success", "not_supported", "failed").
   * The REST handler already emits this key via routedResponse().
   * </pre>
   *
   * <code>string outcome = 4 [json_name = "outcome"];</code>
   * @return The bytes for outcome.
   */
  com.google.protobuf.ByteString
      getOutcomeBytes();

  /**
   * <pre>
   * The routing path taken (e.g. "sdk_only", "cloud_only"). Emitted by routedResponse().
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <pre>
   * The routing path taken (e.g. "sdk_only", "cloud_only"). Emitted by routedResponse().
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
